### ISSUE TITLE
[Bug]: Missing Colors for Breps

### ISSUE THREAD

**Issue by muren400** [ThatOpen/engine_web-ifc#1004]
### What happened?

Hi,

I have [this Model](https://github.com/user-attachments/files/16659609/brep_colors.zip) where IfcStyledItem references an IfcOpenShell instead of the IfcShellBasedSurfaceModel.

```
#436231=IFCOPENSHELL((#436236,#436241,#436247,#436253,#436259,#436265,#436270,#436276,#436282,#436288,#436294,#436300,#436306,#436312,#436318,#436324,#436330,#436336,#436342,#436348,#436353,#436359,#436364,#436369,#436375,#436381,#436387,#436393,#436399,#436405,#436411,#436417));
#565063= IFCCOLOURRGB($,1.,1.,1.);
#565064= IFCSURFACESTYLERENDERING(#565063,0.,$,$,$,$,$,$,.NOTDEFINED.);
#565065= IFCSURFACESTYLE($,.BOTH.,(#565064));
#565066= IFCPRESENTATIONSTYLEASSIGNMENT((#565065));
#565067= IFCSTYLEDITEM(#436231,(#565066),$);
```

Unfortunately IfcGeometryProcessor.GetBrep() doesn't get any color information from the brep (IfcOpenShell) wich leads to the element using the default color.

### Version

0.57

### Anything else?

This is what it should look like:
![image](https://github.com/user-attachments/assets/beca5af1-841a-405b-aaa5-c982fd025950)

This is what it looks like:
![image](https://github.com/user-attachments/assets/995ff95d-d87e-4da2-8dce-c819e1ba15c2)

**Comment by beachtom** [comment]
This is now fixed!
