### ISSUE TITLE
[Bug]: Incorrect display of the element

### ISSUE THREAD

**Issue by MyTh1c2L** [ThatOpen/engine_web-ifc#1023]
### What happened?

Hi, i am using your parser to display models and found a problem with the construction of some elements. Results of two parsers - yours and BimVision. 
I also attach ifc file with this element. [trouble_element.zip](https://github.com/user-attachments/files/16977614/trouble_element.zip)

### Web-IFC
![1](https://github.com/user-attachments/assets/0bec2baa-ff84-4749-bdf4-a9204ad69406)

### BIM-Vision
![2](https://github.com/user-attachments/assets/7e2b7c9a-16de-4104-8615-411d4aa3a101)

### Version

0.57

**Comment by QuimMoya** [comment]
![image](https://github.com/user-attachments/assets/d6152f7c-0510-4e7d-9c43-8f93d1e843f1)
Solved: The issue was caused by a problem in line 106 of curve-utils.h.

**Comment by MyTh1c2L** [comment]
Hello again.
The problem above has indeed been solved, thank you. 
But testing a few more different models a some more elements were found whose display is incorrect. 
I also attach an archive ([trouble elemnts 2.zip](https://github.com/user-attachments/files/17013277/trouble.elemnts.2.zip)) with the problematic elements and screenshots from web ifc viewer and BIM vision.

First.
**Should be**
![11](https://github.com/user-attachments/assets/4be34925-bd95-4a15-906a-16be9caa9b7e)
**Web-IFC**
![12](https://github.com/user-attachments/assets/a7d3797f-a5c2-4d56-81f3-7ad6fc739076)

Second.
**Should be**
![21](https://github.com/user-attachments/assets/330f46f1-926b-4600-8661-f8804f4cb7be)
**Web-IFC**
![22](https://github.com/user-attachments/assets/d09698d2-92fe-4f62-b832-bcaff0d3cd6d)

**Comment by QuimMoya** [comment]
Wall
![image](https://github.com/user-attachments/assets/532a1dff-44f7-4134-bfca-a68d73bacc2c)
Slab
![image](https://github.com/user-attachments/assets/8f539b4d-c81d-4682-a870-0be31fc10511)


Some improvement
