### ISSUE TITLE
[Bug]: Geometry - some reinforcing bars with unexpected representation

### ISSUE THREAD

**Issue by andy-wrks** [ThatOpen/engine_web-ifc#1029]
### What happened?

These are 3 IfcReinforcingBar entities with unexpected geometry that I extracted from a larger model.
The model has originally been created with Revit 2024.
The sample is attached.

Current output:
Screenshot from https://thatopen.github.io/engine_web-ifc/demo/

![image](https://github.com/user-attachments/assets/62b5da9f-225b-475f-a401-41d5b07652ef)

Expected output:
Screenshot from BIMcollab (I also tested some other viewers, they all look like this):

![image](https://github.com/user-attachments/assets/15a77bdc-146e-4571-8389-96834abe8b7b)

Thanks for looking into it!

### Version

0.57

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
There are no errors while loading the model:

web-ifc-viewer.js:266974 Reading took 0 ms
web-ifc-viewer.js:266981 Opening model took 7 ms
web-ifc-viewer.js:92125 Loading 100 geometries and 0 transparent geometries
web-ifc-viewer.js:92142 Uploading took 63 ms
web-ifc-viewer.js:266993 Alignments:  []length: 0[[Prototype]]: Array(0)
```

### Anything else?

[sample_small.zip](https://github.com/user-attachments/files/17029288/sample_small.zip)

**Comment by QuimMoya** [comment]
The issue was resolved; it was caused by a problem with arcs.

![image](https://github.com/user-attachments/assets/cc8739c7-3ebb-4a74-bc91-19b3f6d15973)

**Comment by andy-wrks** [comment]
Wow, that was quick, thanks! Looking forward to the next release :-)
