### ISSUE TITLE
[Bug]: Unexpected token '<'

### ISSUE THREAD

**Issue by Wizer21** [ThatOpen/engine_web-ifc#1051]
### What happened?

Hello ! 

I'm working on a vite/vue.js project where I load IFC models into Three.js, and this part work fine.

But I'd like to add these two lines in my vite config so my application can use 'SharedArrayBuffer'
![image](https://github.com/user-attachments/assets/874bc2b4-0eee-41d5-afd9-c7a9095fc0e2)

And I get the following error
![image](https://github.com/user-attachments/assets/a6c38447-c15d-406b-b409-7e5753ed09c0)
![un expected token](https://github.com/user-attachments/assets/606b8ba4-6e90-4a48-bee5-05c16db79088)

Versions
vue 3.5.4
vite 5.4.4
web-ifc 0.0.58
@thatopen/components 2.2.11

### Version

0.0.58

**Comment by beachtom** [comment]
it looks like your server is returning an error when web-ifc tries to fetch the worker javascript - you can look in the network console about this

**Comment by beachtom** [comment]
No response heard so closing
