### ISSUE TITLE
[Bug]: ifc model is not displayed in demo app

### ISSUE THREAD

**Issue by onderilkesever** [ThatOpen/engine_web-ifc#1055]
### What happened?

Hi! 
I am uploading an IFC model to the demo app(https://thatopen.github.io/engine_web-ifc/demo/), but not able to visualize it. No errors on the console, or on the UI. But model is simply missing. Can you please have a look and let me know if its a bug or I am missing something?
Model : https://drive.google.com/file/d/1XIrGAAYptdDavw1pJEnBQUsP9yUUQlLN/view?usp=sharing
Thanks! 

### Version

0.0.59

**Comment by QuimMoya** [comment]
Hello,

The issue is caused by a void geometry.

When WebIFC tries to center the model using the first point of the first model, it fails because the geometry is empty.

I am working on a solution.

**Comment by onderilkesever** [comment]
Thanks for quick investigation here @QuimMoya. I wonder where can I follow the solution given this issue is closed?
