### ISSUE TITLE
[Bug]: Incorrect geometry. IfcWall with IfcOpeningElement

### ISSUE THREAD

**Issue by MyTh1c2L** [ThatOpen/engine_web-ifc#1057]
### What happened?

Hello again.

I don't remember if this error occurred on earlier versions, but I don't think so.

The problem is as follows. If, for example, there is a hole in the wall described with IfcOpeningElement, the geometry of the wall becomes incorrect. If IFCRELVOIDSELEMENT for a particular wall is removed, then everything is fine.

Ifc file - [trouble opening element.zip](https://github.com/user-attachments/files/17160342/trouble.opening.element.zip) (I left only a few OpeningElements for the two Walls in the file)

**Without IfcOpeningElement:**
![without opening](https://github.com/user-attachments/assets/9b4b208f-890c-4cae-83a2-2054fa9b1c3b)

**With IfcOpeningElement:**
![with opening](https://github.com/user-attachments/assets/f398326d-c108-43db-b5b7-66cba6fd33b0)

### Version

0.58 & 0.59

**Comment by QuimMoya** [comment]
We found what was causing this issue and applied a solution, but we still have to test it extensively.
![image](https://github.com/user-attachments/assets/31c9873a-3e7a-4bb3-aff3-34ef4d283496)

**Comment by Br0wens** [comment]
Hi everyone,

I want to add some research on similar cases.

If we use the "Edit Profile" option in Revit, everything works fine. However, if we use a void element for cutting, some issues appear.
![image](https://github.com/user-attachments/assets/8877de4f-aa93-4e60-beb2-6b940782fc4a)
![image](https://github.com/user-attachments/assets/9934acb4-8d96-47b2-aba2-dbbab7196047)

When using a void element to cut walls, if we change the IFC Class from IfcWindow to IfcVoidingFeature and export using IFC 2x3, the openings are correct.
However, if we use the IfcWindowClass or export in a version other than 2x3, the openings are incorrect.
![image](https://github.com/user-attachments/assets/73d58173-71e4-474c-a32d-aea80964c039)
![image](https://github.com/user-attachments/assets/a9e2faf3-2102-4318-befb-3b5202b4b3fa)

Another problem occurs with non-wall elements.
We have a floor with slopes, and one edge is very close to the floor boundary:
![image](https://github.com/user-attachments/assets/1283930d-fe0e-40a0-81a0-189ddaffbe96)
![image](https://github.com/user-attachments/assets/37a1edf8-1656-496c-98b1-4874a7cef71e)

The result is:
![image](https://github.com/user-attachments/assets/a632cc87-cf24-411d-9311-f80108f2cd26)

We edited the IFC file in Notepad, moving the point that was 3mm away from the floor edge, and everything was correct.

**Comment by QuimMoya** [comment]
If you can share these files, it will be useful to us.

**Comment by Br0wens** [comment]
Test IFC format file:

**Comment by QuimMoya** [comment]
Which ones are supposed to be failing? I opened all of them, and nothing seems to be wrong at first glance.

**Comment by Br0wens** [comment]
IFC 2.2 even do not open :D
All  IFC 2.3 open and wall that i changed IFC Class are correct
IFC 4 and other all walls are incorrect
Every IFC file don't open correct floor element.

**Comment by robertbiskup** [comment]
@QuimMoya which version are you using and is it ok? 
I'm testing on web-ifc  https://unpkg.com/web-ifc@0.0.58 and "@thatopen/components-front": "2.2.2",
"@thatopen/components": "2.2.11"

**Comment by QuimMoya** [comment]
The first model can't be opened because it is in an older version of IFC that we do not support. However, if you edit the IFC file and change FILE_SCHEMA(('IFC2X2_FINAL')) to FILE_SCHEMA(('IFC2X3')), the file should open normally.

To open these files, I'm using the demo:

https://thatopen.github.io/engine_web-ifc/demo

**Comment by Br0wens** [comment]
> @QuimMoya which version are you using and is it ok? I'm testing on web-ifc https://unpkg.com/web-ifc@0.0.58 and "@thatopen/components-front": "2.2.2", "@thatopen/components": "2.2.11"

Thank you very much for answear :) Indeed all files show correct.

**Comment by robertbiskup** [comment]
Hmm, what's the difference between this demo and components.get(OBC.IfcLoader) with default settings?

**Comment by robertbiskup** [comment]
With version .59 I have the same issue using OBC.IfcLoader, what am I doing wrong? It could be something in components?
![image](https://github.com/user-attachments/assets/b422faf7-502a-481b-b5fe-274c797c20a0) 
![image](https://github.com/user-attachments/assets/adca53d6-60a1-4926-8026-caf2a58ee6df)

**Comment by Br0wens** [comment]
> @QuimMoya With version .59 I have the same issue using OBC.IfcLoader, what am I doing wrong? It could be something in components? ![image](https://private-user-images.githubusercontent.com/87365468/372406808-b422faf7-502a-481b-b5fe-274c797c20a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3ODQxNzAsIm5iZiI6MTcyNzc4Mzg3MCwicGF0aCI6Ii84NzM2NTQ2OC8zNzI0MDY4MDgtYjQyMmZhZjctNTAyYS00ODFiLWI1ZmUtMjc0Yzc5N2MyMGEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDExNTc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2NTFiMjI0MTlhOGE3OWVlYmM3NzQ1NjM3ZDUzYjQ2NTVhMjJhYWE5ZGNjYjE0YzJjNDI3MzAyZDE5ZWI3ZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1omH0rAFOU5HNbY8XqhLWH2f7kQjaHQoBZLE5ptLlI4) ![image](https://private-user-images.githubusercontent.com/87365468/372407079-adca53d6-60a1-4926-8026-caf2a58ee6df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3ODQxNzAsIm5iZiI6MTcyNzc4Mzg3MCwicGF0aCI6Ii84NzM2NTQ2OC8zNzI0MDcwNzktYWRjYTUzZDYtNjBhMS00OTI2LTgwMjYtY2FmMmE1OGVlNmRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDExNTc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4MDIwNmY4MDQyNDk4YjczODMxN2U4YWNiYjVmODg5NDFiNzNkMDQzM2NkYWFjMjgxZDRkMWE2YmRkOGUxOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YbkRy0r3HbbQrToQk8zD40FgUv0q_ErGcDCaY6GoG98)

Podłączam się do pytania.

**Comment by QuimMoya** [comment]
Hi, sorry for the delay.

Here we are working with the geometrical engine, but thatopen works with the latest release. This means you may encounter differences between the demo and the thatopen engine, but these differences will disappear over time.

**Comment by QuimMoya** [comment]
What’s important is that your models should open correctly with the [demo](https://thatopen.github.io/engine_web-ifc/demo).

If this is not the case, please share your models, if possible, so we can review and fix any bugs.

**Comment by robertbiskup** [comment]
@QuimMoya thank you, we are waiting for the release of components in version 2.3  ;)
