### ISSUE TITLE
[Bug]: Model processing makes browser freeze

### ISSUE THREAD

**Issue by hellghostx** [ThatOpen/engine_web-ifc#1093]
### What happened?

While model is processing, there is some problem, which makes the browser freeze/stuck.

This also happens within your demo and there is no information in dev tools.

### Version

0.0.61

### What browsers are you seeing the problem on?

Firefox, Chrome

### Anything else?

[model_processing_freeze.zip](https://github.com/user-attachments/files/17492303/model_processing_freeze.zip)

**Comment by QuimMoya** [comment]
![image](https://github.com/user-attachments/assets/6bfc931b-0146-402b-a400-7fbcb921c592)
I got it opened, but it's the latest commit version, not the 0.61 release.

**Comment by hellghostx** [comment]
Back in October it worked fine. Today I am unable to open it again and browser freeze/stuck have returned. 

I have tested it via the demo and also at my end for versions 0.0.66 and 0.0.64 afterwards, with the same results.
