### ISSUE TITLE
[Bug]: Import with webpack

### ISSUE THREAD

**Issue by andrewvarga** [ThatOpen/engine_web-ifc#1114]
### What happened?

This is probably not a bug, but I'm having a hard time setting up the library while importing dynamically. Note: I tried with static import and it seems to be the same result so it's not about dynamic import that's causing this..

This is my TS code after adding `web-ifc` to package.json:
```typescript
const WebIFC = (await import("web-ifc")); // dynamic import to avoid increasing the initial bundle size
const api = new WebIFC.IfcAPI(); // works until this point
await api.Init(); // this is where I'm getting problems
```

I'm getting missing files on the network tab: `web-ifc-mt.worker.js` and `web-ifc-mt.wasm` which I understand is the multithreaded version. So I'm copying those files to where they are missing in my custom build script (which runs webpack also).
Now I can get past that but I'm getting this runtime error:
```javascript
worker sent an error! http://localhost:8888/ifctest/build/dev/src/web-ifc-mt.worker.js:1: Uncaught ReferenceError: WebIFCWasm is not defined
```

I'm guessing the worker file is searching for a global WebIFCWasm symbol but it's not present.
Is there anything wrong in my setup?
When is the decision made to use the multithreaded version? In the examples I saw it was the non multithreaded `web-ifc.wasm` being used and others also used web-ifc-api-iife.js instead of the one currently imported dynamically: `web-ifc-api.js`.

Any pointers would be very helpful.
Thanks

### Version

0.0.61

### What browsers are you seeing the problem on?

Chrome

**Comment by andrewvarga** [comment]
Found the answer to this question: "When is the decision made to use the multithreaded version?"
```javascript
  var WebIFCWasm;
  if (typeof self !== "undefined" && self.crossOriginIsolated) {
    try {
      WebIFCWasm = require_web_ifc_mt();
    } catch (ex) {
      WebIFCWasm = require_web_ifc();
    }
  } else WebIFCWasm = require_web_ifc();
```

**Comment by beachtom** [comment]
So to be honest I see very few cases where the MT versions is actually allowed to by a setup and when it does it provides little performance imporvement.

Was using the mt-version your intention? Or do you just want to get it working?

**Comment by andrewvarga** [comment]
I just wanted it to get to work, although I do have a large 150MB+ ifc file which does freeze the browser for 10-15 seconds and I thought MT could help (I can send you the file if that's useful).
Eventually I could get the single threaded version to work by this huge hack, but it would be good to be able to do it a cleaner way, either being able to use MT or turning it off with a config.
```typescript

const originalGetter = Object.getOwnPropertyDescriptor(self, 'crossOriginIsolated')?.get;
Object.defineProperty(self, 'crossOriginIsolated', {
   get: function() { return false; }
});

const {IfcAPI} = await import("web-ifc");
const api = new IfcAPI();

await api.Init();

Object.defineProperty(self, 'crossOriginIsolated', {
   get: originalGetter
});
```

**Comment by beachtom** [comment]
I am not entirely sure why the MT version is failing at the moment, but I will add a config flag to disable it.

The MT version will not help with that 10-15s freeze currently.
