### ISSUE TITLE
[Bug]: Model doesn't load

### ISSUE THREAD

**Issue by jespa007** [ThatOpen/engine_web-ifc#1120]
### What happened?

I've an issue with this IFC [241104_IfcNotLoaded.zip](https://github.com/user-attachments/files/17621046/241104_IfcNotLoaded.zip). The problem is that when it tries to get their meshes through IfcApi.StreamMeshes, is stuck forever. I've test the last version that it works is the version 0.58, so this bug happens since 0.59.

 The model rendered is shown below (loaded in BIMcollab Zoom),

![image](https://github.com/user-attachments/assets/01fb99f8-cab7-42cb-b399-08f4eb700c9e)

Possible duplicate of #1069

### Version

Latest

### What browsers are you seeing the problem on?

Chrome

### Anything else?

All information given in the description

**Comment by QuimMoya** [comment]
We found a solution for it, but we have to make some tests before updating
![image](https://github.com/user-attachments/assets/8e7856b7-ac5c-417f-85fb-fb2767390c66)
