### ISSUE TITLE
"[Feat]: Dockerized image for engine_web-ifc for a demo or example quick setup

### ISSUE THREAD

**Issue by Ibrahimgabrieel** [ThatOpen/engine_web-ifc#1121]
### What is your idea?

My idea is to set up all the dependecies and dockerize them to speed up the setup process,I don't know if it exists or not. I searched a lot, but I didn't find anything

**Comment by beachtom** [comment]
So it does already exist - you just need to run npm run docker-build" and then npm run docker-get-compiled-files.

Please re-open if its not working as expected for you
