### ISSUE TITLE
How do I get IFC Geometries?

### ISSUE THREAD

**Issue by SoftwareMechanic** [ThatOpen/engine_web-ifc#1136]
### What happened?

I don't know if I am missing some parts of the documentation, this is what I am trying:

```
       var testModel = this.IFCAPI.OpenModel(bin)
        let allGeom = this.IFCAPI.LoadAllGeometry( testModel)

        

        for (let i = 0; i < allGeom.size(); i++) {
            const geometry = allGeom.get(i).geometries;
            for (let j = 0; j < geometry.size(); j++) {
                const geom = geometry.get(j);
                var g = this.IFCAPI.GetGeometry(testModel, geom.geometryExpressID)
                g.GetVertexData()
                console.log(g.GetVervtexData());
            }
        }
```

but I just end up with some numbers, shouldn't I got a list of vertices and indices?

### Version

0.0.51

**Comment by beachtom** [comment]
You need to call something like: 

        const verts = this.ifcAPI.GetVertexArray(geom.GetVertexData(), geom.GetVertexDataSize());
        const indices = this.ifcAPI.GetIndexArray(geom.GetIndexData(), geom.GetIndexDataSize());

This should let you get the vertexes and indicies etc...

**Comment by SoftwareMechanic** [comment]
thank for your answer! :100: 
I was also wondering how the same behavior is  possible to do in c++ side, so 'converting' the VertexData and DataSize in an array.
I don't see how these methods are exposed to the wasm, sorry for that.
