### ISSUE TITLE
[Bug]: Error loading web-ifc.wasm file

### ISSUE THREAD

**Issue by daker** [ThatOpen/engine_web-ifc#1138]
### What happened?

I am using webIFC package in vtk.js with the following code :

```js
vtkResourceLoader
  .loadScript('https://cdn.jsdelivr.net/npm/web-ifc@0.0.61/web-ifc-api-iife.js')
  .then(() => {
    // Pass WebIFC api to vtkIFCImporter
    vtkIFCImporter.setIFCAPI(window.WebIFC);

    // Trigger data download
    importer
      .setUrl(
        'https://raw.githubusercontent.com/ThatOpen/engine_web-ifc/refs/heads/main/tests/ifcfiles/public/duplex.ifc'
      )
      .then(update);
  });

// vtk.js code
model._ifcApi = new WebIFC.IfcAPI();
model._ifcApi.Init().then(() => {
      parseIfc(content);
      publicAPI.invokeReady();
});
```

using 0.0.61 the wasm file is loaded from jsdelivr

![image](https://github.com/user-attachments/assets/5fc84b11-f633-4108-be3d-3cdcee5a0d7f)

but if i switch to 0.0.62 it's trying to load the wasm from my webserver

![image](https://github.com/user-attachments/assets/a5bbfef6-5d0d-460a-b5e1-9a7244b9f1a7)

### Version

0.0.62

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by beachtom** [comment]
Can you share the code where you initialise web-ifc ? The .Init(....)

**Comment by daker** [comment]
@beachtom, here is the PR

https://github.com/Kitware/vtk-js/pull/3168/files#diff-a19d54be666c1dc304093a47769229cc37f68acc1209e4f6022f6898452ce28bR237-R242

**Comment by beachtom** [comment]
OK I've fixed it so it should behave as before - this will be in the newest release
