### ISSUE TITLE
[Bug]: Fix Pathing (#1145) breaks my app

### ISSUE THREAD

**Issue by peterhirn** [ThatOpen/engine_web-ifc#1153]
### What happened?
~~https://github.com/ThatOpen/engine_web-ifc/commit/b71489098c83fba144d5ebebff0313210c395362#r149265602~~

This commit breaks my app: https://github.com/ThatOpen/engine_web-ifc/commit/aa1346d812844c6e4fb989374d8693d97201f80b

```
TypeError: Cannot read properties of null (reading 'src')
```

### Version

0.0.64

**Comment by beachtom** [comment]
Fixing this shortly. Will be out later tonight.
