### ISSUE TITLE
[Bug]: Parsing error in web-ifc when encountering * in IFC file

### ISSUE THREAD

**Issue by powerocean** [ThatOpen/engine_web-ifc#1160]
## Description
I encountered an issue with `web-ifc` where it fails to correctly parse IFC files containing the `*` symbol in certain fields. According to the IFC standard, `*` is a valid placeholder for an undefined value, but `web-ifc` does not seem to handle it properly. This leads to incorrect parsing results, especially when parsing relationships such as `IFCRELAGGREGATES`.
Here is an example of a problematic IFC snippet:
`
#1 = IFCRELAGGREGATES('BohvtDLAfw6mzz2U8Z3f8j', *, $, $, #2, (#12));
`
and
`
#13 = IFCRELCONTAINEDINSPATIALSTRUCTURE('Ey9YGvNEs4iJHMHGM1vuJq', *, $, $, (#14), #12);
`

## Expected Behavior
- The `RelatingObject` should be parsed as:  ` { "value": 2, "type": 5 }`
- The `RelatedObjects` should be parsed as: `[{ "value": 12, "type": 5 }]`
## Actual Behavior
Due to the presence of *, the parser incorrectly returns:
-  `RelatingObject` : `{ "value": undefined, "type": 5 }`
-  `RelatedObjects`: `[]`

## Steps to Reproduce:
1. Use the following IFC snippet (or a file containing it) with web-ifc:
`#1 = IFCRELAGGREGATES('BohvtDLAfw6mzz2U8Z3f8j', *, $, $, #2, (#12));`
2. Attempt to parse the file using web-ifc.
3.  Check the parsed values of `RelatingObject` and `RelatedObjects`.

## Proposed Solutions:
1. Modify the parser to treat `*` as a `$` value or equivalent during processing.
2. Ensure that subsequent fields are correctly parsed even when * is encountered.

### Version

0.0.65

### Relevant log output

```shell
ERROR: Invalid IFC Line:2
Uncaught TypeError: v[7]?.map is not a function
```

### Anything else?

[snippet.zip](https://github.com/user-attachments/files/17829707/snippet.zip)

**Comment by beachtom** [comment]
So * should only be used if the class of the object has set that property to a derived property. These should parse - if they don't please let me know

So looking at your example file its use in IFCSIUnit is valid - but its use in IFCBuilding and the others is incorrect - and they should be set to $

**Comment by powerocean** [comment]
Okay, I understand. I found that this IFC file can be parsed by BIMvision correctly, and I guess it might have implemented some special logic to ignore this IFC syntax error.
