### ISSUE TITLE
Geometry: missing hole in floor covering

### ISSUE THREAD

**Issue by andy-wrks** [ThatOpen/engine_web-ifc#299]
The sample file contains an IfcSlab with an IfcCovering on top of it. The IfcCovering is an aggregate element and consists of two IfcBuildingElementParts. These two IfcBuildingElementParts should each have a hole (in the area enclosed by the walls and in front of the wall openings). These holes are missing however.
The file was originally exported from ArchiCAD 24.

The issue can be reproduced on
https://ifcjs.github.io/web-ifc-viewer/example/index and
https://ifcjs.github.io/web-ifc-three/example/

Current output:
![image](https://user-images.githubusercontent.com/111515188/209962034-44421ffe-ce7e-47bc-bfd9-0dc4424e41f6.png)

Expected output:
![image](https://user-images.githubusercontent.com/111515188/209961940-a93a7d24-9635-40ab-9a56-0e3a84faa8ef.png)

Sample file:
[ArchiCAD-24_missing_hole.zip](https://github.com/IFCjs/web-ifc/files/10319731/ArchiCAD-24_missing_hole.zip)

**Comment by andy-wrks** [comment]
I'm updating this with screenshots from the updated https://ifcjs.github.io/web-ifc/demo/
The output changed, but is still broken.

Current output (https://ifcjs.github.io/web-ifc/demo/):

![image](https://user-images.githubusercontent.com/111515188/220616211-73056ae2-e908-4026-9796-fabe6e032c42.png)
![image](https://user-images.githubusercontent.com/111515188/220616060-3a618436-f4de-4023-8547-0e00330eefe3.png)

Expected output (BIMcollab):
![image](https://user-images.githubusercontent.com/111515188/220616359-77e1dab0-c1fd-44e7-af78-8aaab92abb1d.png)
![image](https://user-images.githubusercontent.com/111515188/220616608-30ab1205-05d9-4dbc-b6ce-2224a9039938.png)

**Comment by andy-wrks** [comment]
I'm updating this, because the output changed once again, but is still broken.

Output in 0.0.43 wip:

![image](https://github.com/IFCjs/web-ifc/assets/111515188/b8e10118-5952-4a1c-b2b6-3d5a8d84483a)

(1) This should be a hole
(2) The surface along the edge is see-through, so probably there's an inverted normal here.

Issue (1) from below:

![image](https://github.com/IFCjs/web-ifc/assets/111515188/263b31c4-ee5e-4892-b337-4bf500dd6950)

**Comment by QuimMoya** [comment]
![image](https://github.com/user-attachments/assets/ae35d662-3a85-4f0f-9a56-f234f2cc27a9)

Finally solved!!
