### ISSUE TITLE
Incorrect shadows

### ISSUE THREAD

**Issue by QuimMoya** [ThatOpen/engine_web-ifc#306]
Some models expose incorrect shadows 
![image](https://user-images.githubusercontent.com/12625508/211471688-d92b49ee-3c9c-4cce-a8a7-1e1e92177bcf.png)

This image shows shadows in non-visible faces of the model.
Shadows must be applied on the visible faces only

**Comment by agviegas** [comment]
I think that this can be fixed by using 2-face Three.js materials.

**Comment by aka-blackboots** [comment]
@QuimMoya can you attach the IFC file for reference

**Comment by beachtom** [comment]
@QuimMoya can you check this model again - I think a PR has fixed many issues to do with shadows
