### ISSUE TITLE
[Bug]: String encoding - problem with special characters (v2)

### ISSUE THREAD

**Issue by Tamu** [ThatOpen/engine_web-ifc#368]
### What happened?

In Revit 22.1+ Autodesk to replaced the IFC export module.
The new version have therefore changed the format for special characters (ISO-10303) :

Special characters : é
Old format (ok with IFCjs) :  `\X2\00E9\X0\`
New format :   `\X\E9`

### Version

0.0.34

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
no logs
```

### Anything else?

Similar issue : [Issue 58](https://github.com/IFCjs/web-ifc/issues/58)
Probably the same subject : [issue 358](https://github.com/IFCjs/web-ifc/issues/358)
Original source from Revit IFC : [Revit-ifc](https://github.com/Autodesk/revit-ifc/issues/441)

**Comment by Tamu** [comment]
With the inspiration of @kovacsv code, I extended the function (with the dirty solution on the JavaScript side) :

```JavaScript 
function DecodeIFCString (ifcString)
{
    let resultString = ifcString;

    const ifcUnicodeRegEx = /\\X2\\(.*?)\\X0\\/uig;   //  \X2\00E9\X0\
    let match = ifcUnicodeRegEx.exec(ifcString);
    while (match) {
        const unicodeChar = String.fromCharCode (parseInt (match[1], 16));
        resultString = resultString.replace (match[0], unicodeChar);
        match = ifcUnicodeRegEx.exec (ifcString);
    }

    const ifcUnicodeRegEx2 = /\\X\\(.?)(.?)/uig;  //  \X\E9
    let match2 = ifcUnicodeRegEx2.exec(ifcString);
    while (match2) {
        const unicodeChar = String.fromCharCode (parseInt (match2[1] + match2[2], 16));
        resultString  = resultString.replace (match[0], unicodeChar);
        match2 = ifcUnicodeRegEx2.exec (ifcString);
    }

    return resultString;
}
```

**Comment by beachtom** [comment]
So for me this is working in the current version on main at the moment  - are you able to try it with this?

**Comment by Tamu** [comment]
Hi @beachtom,
Thanks for your confirmation. According to my test today, I confirm that it should work with the latest version.

On the other hand, I'm blocked to test the last web-ifc in web-ifc-three, is there a code example which contains the last version of web-ifc + web-ifc-three?

Big thanks !

**Comment by beachtom** [comment]
So the current web-ifc on its main should be 0.0.39 which should have fixed this. Unfortunately I am not that familiar with web-ifc-three architecture - so probably best to raise an issue there? Can you re-open if 0.0.39 doesn't fix it?

**Comment by Tamu** [comment]
Thanks @beachtom ! I will do the tests on the web-ifc-three side.
