### ISSUE TITLE
[Bug]: Errors in representation of IFC models

### ISSUE THREAD

**Issue by smout74** [ThatOpen/engine_web-ifc#380]
### What happened?

Hi,

In the latest update of web-ifc/web-ifc-viewer there are representation issues/errors, some of them were not present in earlier releases.

1. Hole is probably in the correct position
2. L-profile is orientated wrong
3. Why is this area black ?  (light issue ?)
4. Why are these welds black ?  (light issue ?)
5. Wrong model

In a previous version point 5 was fixed. (0.0.35 ?)

![image](https://user-images.githubusercontent.com/39618522/233632190-00f054d4-af89-46f5-ad40-aec37fc1d6e7.png)
![image](https://user-images.githubusercontent.com/39618522/233632224-164c89b9-5c82-4524-8d74-eec628b08521.png)
![image](https://user-images.githubusercontent.com/39618522/233632422-6b1e8672-e43f-4ec2-bcd2-f05b4b8ebf6d.png)

It should be like this
![image](https://user-images.githubusercontent.com/39618522/233632581-d9efb60f-c6d8-4fe2-8471-7f0e1d6a7bf4.png)
![image](https://user-images.githubusercontent.com/39618522/233632658-ff98bd55-7f09-4cbe-a498-dfb0a51d79ba.png)
![image](https://user-images.githubusercontent.com/39618522/233632736-2fe1daba-9e5c-43a0-9d6f-c49de039ace8.png)

Also this is not correct:
![image](https://user-images.githubusercontent.com/39618522/233633449-6712ae27-ec6e-4026-bf8c-65d7c9edfde8.png)
Should like this
![image](https://user-images.githubusercontent.com/39618522/233633501-5520e262-ff25-4a6c-902d-64c422772a0a.png)

In another model
![image](https://user-images.githubusercontent.com/39618522/233634304-96a09d3b-3909-4ace-9126-ca72f639db89.png)
Should be like this
![image](https://user-images.githubusercontent.com/39618522/233634427-48dae348-906f-4fee-aa94-ec4c7f41a633.png)
And this
![image](https://user-images.githubusercontent.com/39618522/233639377-02e0493b-4435-418a-a663-c7b5dcb991cc.png)
Should be like
![image](https://user-images.githubusercontent.com/39618522/233639556-45a6274d-21c9-4812-913c-39ea49d09402.png)

It looks like most issues are from Tekla software generated IFC's (modelling program). Maybe the negative volumes are an issue ?
https://www.tekla.com/products/tekla-structures
[K64.zip](https://github.com/IFCjs/web-ifc/files/11295813/K64.zip)

All of the modelsshow errors in all 3 web demo's (web-ifc, web-ifc-viewer, web-ifc-three)

### Version

0.0.39

### What browsers are you seeing the problem on?

Firefox, Chrome

**Comment by smout74** [comment]
I see in version 0.0.41 some progress. Following errors seem to be correct now:

![image](https://github.com/IFCjs/web-ifc/assets/39618522/25d50b22-b8fe-4767-ad6e-5d3293c9fd2b)

![image](https://github.com/IFCjs/web-ifc/assets/39618522/864170a4-c3d1-4abf-8a72-ba5f44d617c3)

Thanks and keep up the good work 👍🏻

**Comment by QuimMoya** [comment]
![image](https://github.com/IFCjs/web-ifc/assets/12625508/46ac04ac-f40e-4e8c-b6c6-4192581dfff2)

Solved in the last commit

**Comment by QuimMoya** [comment]
The first link pointing to tekla sturctures does not work. I will solve other issues when i can access the file.

**Comment by smout74** [comment]
> The first link pointing to tekla sturctures does not work. I will solve other issues when i can access the file.

That was just a link to the program itself.
The model is included here now.
[constructie1.zip](https://github.com/IFCjs/web-ifc/files/11950658/constructie1.zip)

**Comment by smout74** [comment]
in version 0.0.43 there are still some issues with the ifc models.

in BimVision:
![image](https://github.com/IFCjs/web-ifc/assets/39618522/8678c505-dc32-4eee-8e3c-07edc4bd1dfa)

in web-ifc:
![image](https://github.com/IFCjs/web-ifc/assets/39618522/a5a0d421-e7a1-4372-a878-c0d8ea8f3a90)
![image](https://github.com/IFCjs/web-ifc/assets/39618522/57b2fe37-eb2b-47c1-a16d-3bc2db5882a1)

And of course the problems of the first model in the first post are also still present (except rotation of L-profile)

Models in .zip

[constructions.zip](https://github.com/IFCjs/web-ifc/files/12550715/constructions.zip)

**Comment by QuimMoya** [comment]
I think this is now fixed
![image](https://github.com/user-attachments/assets/af522ee0-3718-4463-aa24-9b797e17275f)

![image](https://github.com/user-attachments/assets/1d072bea-6b11-4eb7-90b6-042b4c461a54)
