### ISSUE TITLE
IFCViewer doesnt display this ifc model

### ISSUE THREAD

**Issue by jstec** [ThatOpen/engine_web-ifc#384]
I can't display attached ifc using ifcviewer.

[PGM - Bombers Terrassa_CENTRAL v03.zip](https://github.com/IFCjs/web-ifc-viewer/files/11295766/PGM.-.Bombers.Terrassa_CENTRAL.v03.zip)

**Comment by agviegas** [comment]
"Can't display" is a bit ambigous. Can you provide more information? The more you provide, the faster we will be able to solve it.

**Comment by jstec** [comment]
Can't display means file doesn't loads.

**Comment by jespa007** [comment]
Good news @jstec,

With a bit of patience ifcjs was able to load the model

![image](https://user-images.githubusercontent.com/7852409/234213375-6342fcff-444c-4cbf-9e97-8a2a1f2d9060.png)

But it took 8 minutees and 47 seconds.... May be something is not well configured in that IFC-

**Comment by beachtom** [comment]
So yes - this IFC file is generating a lot of errors which is what is slowing it down. I am unsure if these errors are because of bugs in parsing or a problem with the IFC file. Will look into it

**Comment by jstec** [comment]
Thank you @beachtom for looking into

**Comment by QuimMoya** [comment]
@jstec I will take a look too

**Comment by QuimMoya** [comment]
The problem appears to be related to the use of extremely high values during boolean operations.

**Comment by jstec** [comment]
What it means? exemple: the problem appears when comparing A=B and A, B contains numerical high values?

**Comment by QuimMoya** [comment]
The problem seems to improve, the last version opens this models in 1 minute or so.

**Comment by QuimMoya** [comment]
The latest version (test it [here](https://ifcjs.github.io/info/)) opens this model much faster.

**Comment by jespa007** [comment]
> The latest version (test it [here](https://thatopen.github.io/engine_web-ifc/demo)) opens this model much faster.

Thanks Quim!

**Comment by jstec** [comment]
Thanks a lot!!!

Jose Souto
________________________________
De: Antonio González Viegas ***@***.***>
Enviado: lunes, 28 de octubre de 2024 12:02
Para: ThatOpen/engine_web-ifc ***@***.***>
Cc: Jose Souto ***@***.***>; Mention ***@***.***>
Asunto: Re: [ThatOpen/engine_web-ifc] IFCViewer doesnt display this ifc model (Issue #384)


Closed #384<https://github.com/ThatOpen/engine_web-ifc/issues/384> as completed.
