### ISSUE TITLE
[Bug]: Issue with geometry

### ISSUE THREAD

**Issue by rkaeplive** [ThatOpen/engine_web-ifc#426]
### What happened?

I have issues with geometry T-geometry is wrong rotated (1st picture- OpenIFCViewer, 2nd - ifcjs) 
![image](https://github.com/IFCjs/web-ifc/assets/80881455/248bf0be-ef89-49b3-ab98-73e989b1c8af)
![image](https://github.com/IFCjs/web-ifc/assets/80881455/80552df4-f682-4120-bc55-dce2aa46ae92)

and some problems with back side
![image](https://github.com/IFCjs/web-ifc/assets/80881455/5b417c24-43a1-40f6-be0e-11698c070f37)
![image](https://github.com/IFCjs/web-ifc/assets/80881455/a02abc73-b72f-42fc-bb2c-ddeab90e2623)

### Version

"web-ifc-viewer": "^1.0.217"

**Comment by rkaeplive** [comment]
[geometry_issues.Ifc.zip](https://github.com/IFCjs/web-ifc/files/11891495/geometry_issues.Ifc.zip)

**Comment by rkaeplive** [comment]
[geometry_issues.Ifc.zip](https://github.com/IFCjs/web-ifc/files/11891507/geometry_issues.Ifc.zip)

**Comment by QuimMoya** [comment]
I opened your model in IFC.JS
![image](https://github.com/IFCjs/web-ifc/assets/12625508/6fdc7250-795a-41c2-8a79-871c0ae4985a)

And then in Bimvision
![image](https://github.com/IFCjs/web-ifc/assets/12625508/bf55ce77-69e6-4955-8cbe-878b12dd3d29)


While there may be an issue with the expansion of metallic profiles, I have been unable to locate the specific problem you mentioned earlier.

**Comment by QuimMoya** [comment]
Hi, good news, it seems last update solved some issues.

![image](https://github.com/IFCjs/web-ifc/assets/12625508/dd70df4b-4075-48da-9d46-4a078e9098f0)

**Comment by rkaeplive** [comment]
@QuimMoya what version of ifcjs do you use? I use npm install. I can send you the repo of this issue

**Comment by rkaeplive** [comment]
@QuimMoya 
https://github.com/rkaeplive/geometry-issue-three
in this case this T-geometry is rotated
![image](https://github.com/IFCjs/web-ifc/assets/80881455/a5c98931-b049-4e63-abb8-28317abb4f27)
and some bugs with meshes
![image](https://github.com/IFCjs/web-ifc/assets/80881455/1830ac25-0079-40a6-a62d-87d6dbce6ef8)

**Comment by QuimMoya** [comment]
Ik i will look at this

**Comment by QuimMoya** [comment]
The problem with rotated T profiles will be solved in the next release, this week we will do it.
![image](https://github.com/IFCjs/web-ifc/assets/12625508/046ef1d6-2b62-45a7-8079-6f5ab10673da)
But the problem of missing faces is still present in some profiles, i will work on it.

**Comment by rkaeplive** [comment]
Hello, did you solve this?

**Comment by QuimMoya** [comment]
@rkaeplive 

Hello

Sorry for the delay. Yes, the problem of rotated profiles is solved. Not sure if all problems with missing faces are solved.

**Comment by rkaeplive** [comment]
@QuimMoya did you release it ?

**Comment by rkaeplive** [comment]
Hello again, did you solve missing faces issue?

**Comment by QuimMoya** [comment]
@rkaeplive 

Yes, the missing faces should be solved, and the rotated T. We will do a new release soon and many of these problems should became solved
But if you find anything wrong please post the picture, it's easier for us to see exactly where are still problems in the model in order to solve them.

**Comment by rkaeplive** [comment]
@QuimMoya hello again 
Where are many missing faces here, im not use DoubleSide material
<img width="1173" alt="image" src="https://github.com/IFCjs/web-ifc/assets/80881455/637f1e5c-41fc-494d-aa6e-168ef1d8c3b8">
backside is ok 
<img width="935" alt="image" src="https://github.com/IFCjs/web-ifc/assets/80881455/5a995afc-7a3c-4aad-9fec-966ea77f980f">
this file
[Clinic_A.ifc.zip](https://github.com/IFCjs/web-ifc/files/12583732/Clinic_A.ifc.zip)

**Comment by QuimMoya** [comment]
Is it solved now?

![image](https://github.com/user-attachments/assets/6e37e0f8-b2be-4ed7-9215-e8cc93c41ac3)


Please open it with the [demo](https://thatopen.github.io/engine_web-ifc/demo)

Confirm it open Ok and i will close the issue
