### ISSUE TITLE
[Bug]: Roof geometry with bad surfaces

### ISSUE THREAD

**Issue by andy-wrks** [ThatOpen/engine_web-ifc#456]
### What happened?

I attached a sample file with 4 slanted roof elements, each with 2 holes in them.
The elements fail to be converted to closed volumes (see screenshots below).

(Note: In the original file, there is a follow up problem. The walls below the roof aren't clipped. However, I assume this is a direct effect of the roofs being open volumes. In order to keep this Issue report clean, I didn't include the walls, since this problem might solve itself once the roof volumes are fixed.)

Roof1 current output in web-ifc 0.0.43 wip:
![image](https://github.com/IFCjs/web-ifc/assets/111515188/54fac865-0288-49df-a4b2-ceb7554c48c7)

Roof1 expected output:
![image](https://github.com/IFCjs/web-ifc/assets/111515188/2401e29e-ee46-4c76-8277-cabd1d3b208f)

Roof2 current output in web-ifc 0.0.43 wip:
![image](https://github.com/IFCjs/web-ifc/assets/111515188/7d1505ed-cd41-49f8-aa75-32e2116c2dba)

Roof2 expected output:
![image](https://github.com/IFCjs/web-ifc/assets/111515188/784ef686-9163-40aa-90ab-9c14c3c0a9a8)

### Version

0.0.43 wip

### What browsers are you seeing the problem on?

Chrome

### Anything else?

Sample file:
[sample.zip](https://github.com/IFCjs/web-ifc/files/12172688/sample.zip)

**Comment by QuimMoya** [comment]
![image](https://github.com/user-attachments/assets/0af40685-3e14-45c9-be14-ca6bd248bb33)

I think everthing is ok now. I close the issue
