### ISSUE TITLE
[Bug]: Model with artefacts

### ISSUE THREAD

**Issue by hellghostx** [ThatOpen/engine_web-ifc#481]
### What happened?

Model is having several artefacts and in console is a lot of trizero output.

Since model is private, I can share it only through private way, so model has been sent to [ifc.js.contact@gmail.com](mailto:ifc.js.contact@gmail.com) with this issue number in subject.

For comparison in second picture is state of the same model in software BIMvision, which I have been told that should be correct.

### Version

0.0.43

### What browsers are you seeing the problem on?

Chrome

### Anything else?

![modelReport](https://github.com/IFCjs/web-ifc/assets/26725817/9da9b9b0-a695-4521-90e8-082e3aafeee1)

![obrazek](https://github.com/IFCjs/web-ifc/assets/26725817/2e6289f6-5c0e-44e7-a57b-de5437f64036)

**Comment by QuimMoya** [comment]
I think all artifacts have been fixed

![image](https://github.com/user-attachments/assets/13c9fa72-69c3-4788-97b7-e5a42fbb9919)

I will close the issue

**Comment by hellghostx** [comment]
> I think all artifacts have been fixed

It  looks great except this part, which should not be there.

![obrazek](https://github.com/user-attachments/assets/1532a5ab-3b35-424b-81e3-1c2de75f9d34)

**Comment by hellghostx** [comment]
Version 0.0.61 - it gets worse than in 0.0.59

![obrazek](https://github.com/user-attachments/assets/78f06788-be0e-4a3a-aaed-c452fa2a83aa)
