### ISSUE TITLE
Different coordinates from Version 0.0.39 to Version 0.0.40

### ISSUE THREAD

**Issue by agaussen** [ThatOpen/engine_web-ifc#500]
Using the code below, we're producing different coordinates (and flatTransformation matrices) between web-ifc 0.0.39 to later versions.

```javascript
const fs = require('fs');
const WebIFC = require('web-ifc');
const math = require('mathjs');

(async () => {
    const ifcApi = new WebIFC.IfcAPI();
    await ifcApi.Init();
    const ifcData = fs.readFileSync(__dirname + '\\github.ifc');
    const modelID = ifcApi.OpenModel(ifcData, {
        COORDINATE_TO_ORIGIN: false,
        USE_FAST_BOOLS: true
    });
    ifcApi.CreateIfcGuidToExpressIdMapping(modelID);

    // First Guid
    const expressID =  ifcApi.ifcGuidMap.get(modelID).get('2sxwD6Brz$3m00000001$E');
    // Mesh / ExpressID 428
    const mesh = ifcApi.GetFlatMesh(modelID, expressID).geometries;
    const placedGeometry = mesh.get(0);
    console.log(placedGeometry.flatTransformation);

    const FT = placedGeometry.flatTransformation;
    let M = math.matrix([
        FT.slice(0, 4),
        FT.slice(4, 8),
        FT.slice(8, 12),
        FT.slice(12)
    ]);
    // Transform to x,y,z
    const T = [
        [1,  0, 0, 0],
        [0,  0, 1, 0],
        [0, -1, 0, 0],
        [0,  0, 0, 1]
    ];
    const geometry = ifcApi.GetGeometry(modelID, placedGeometry.geometryExpressID);
    const vertices = ifcApi.GetVertexArray(geometry.GetVertexData(), geometry.GetVertexDataSize());
    const V = Array.from(new Set(vertices.slice(0, 3)).add(1));
    const MM = math.multiply(M, T);            
    const pt1 = math.multiply(V, MM);
    console.log(math.squeeze(pt1).toArray());
})();
```

**Version 0.0.39**\
flatTransformation: `(16) [1, 0, 0, 0, 0, 0, -1, 0, 0, 1, 0, 0, 337598.8554351305, 3.784399999999996, -5781624.42302636, 1]`\
pt1  **(x,y,z)**:    `(4) [337599.6818034028, 5781624.475225887, 3.8132999993354044, 1]`

**Version 0.0.40**\
flatTransformation: `(16) [1, 0, 0, 0, 0, 0, -1, 0, 0, 1, 0, 0, 0, 0, 0, 1]`\
pt1 **(x,y,z)**: `(4) [337599.6875, 5781624.5, 3.8132998943328857, 1]`

**Version: 0.0.44 (current)**\
flatTransformation: `(16) [1, 0, 0, 0, 0, 0, -1, 0, 0, 1, 0, 0, 0, 0, 0, 1]`\
pt1 **(x,y,z)**: `(4) [337599.6875, 5781624.5, 3.8132998943328857, 1]`

I'm unsure if the discrepancy in values between `0.0.39` and `0.0.40+` is due to our implementation, but the y values have (predominantly) lost precision (the output values of `0.0.39` match IfcOpenShell output). So far, this is the only file we're having this issue with, but I can't identify any IFC differences (originally created with AutoCAD C3D 2020).

Is there a better combination of OpenModel settings that we should be using with `0.0.40+`? Any assistance is appreciated.

Sample file: [github.ifc ](https://thinkspatialcomau139-my.sharepoint.com/:u:/g/personal/agaussen_thinkspatial_com_au/Efe6XIS2zl5CqkVhlPZhkOEByDK8fDgRBHPPEwLSKyF8Cw?e=l3kEUX)

**Comment by beachtom** [comment]
Hi - so there was issues with the transform matricies in some which have now been fixed. Can you check all is OK and come back to me if not?
