### ISSUE TITLE
[Bug]: Some object colors are wrong

### ISSUE THREAD

**Issue by jschweiker-allplan** [ThatOpen/engine_web-ifc#516]
### What happened?

For some IFC files the color is falsely black in comparion to other viewers.

Placed geometrey is having the black color, so it seems the color information is not correctly extracted during the geometry creation step. 

Data is confidential so I will send it separately.

### Version

0.0.44

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

**Comment by beachtom** [comment]
I think this is now fixed, but I have no model to double check. Please re-open if it is not fixed.
