### ISSUE TITLE
[Bug]: Bspline Representations Not Rendering Properly Across Several Test Files

### ISSUE THREAD

**Issue by nickcastel50** [ThatOpen/engine_web-ifc#520]
### What happened?

It appears BSpline representations aren't working across a handful of test files I've tried. I've sent the test files to @beachtom but they are below for reference:

Link 1: https://github.com/buildingSMART/IFC/blob/master/Examples/Advanced%20geometric%20shape/Examples/Basin%20advanced%20brep/File.ifc

Link 2: https://github.com/buildingSMART/IFC/blob/master/Examples/Advanced%20geometric%20shape/Examples/Cube%20advanced%20Brep/File.ifc

I'm currently doing a deep dive in trying to identify the issue, so far I've noticed this:

It appears BSplineSurface.WeightPoints are set here: https://github.com/IFCjs/web-ifc/blob/689fde101c807a0b8474f014561f153a1a637722/src/wasm/geometry/IfcGeometryProcessor.cpp#L1383 

But in TriangulateBspline, it is trying to iterate over the "Weights" field, which is never set as far as I can tell: https://github.com/IFCjs/web-ifc/blob/689fde101c807a0b8474f014561f153a1a637722/src/wasm/geometry/operations/mesh_utils.h#L623 

Will update as I glean some more information.

### Version

Latest

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by QuimMoya** [comment]
![image](https://github.com/user-attachments/assets/93104c8c-4b13-452b-b5e7-99b5494e5313)
![image](https://github.com/user-attachments/assets/9d4cc1c2-7c3b-4b82-bd9a-dcabf942229d)
Does it work properly now?
