### ISSUE TITLE
Some Models is not displayed well and not show Properties

### ISSUE THREAD

**Issue by pegreal** [ThatOpen/engine_web-ifc#524]
### Describe the bug 📝

I am testing the first non-alpha version of OBC (1.1.0) and I observe that some models IFC, are not displayed correctly, you can see an example in the image, also does not show the properties, in these cases that is not displayed well. 

The code, is the one of the tutorial FragmentIfcLoader + ifcPropertiesProcessor but implemented in React.

left OBC, right web-ifc-viewer
![image](https://github.com/IFCjs/components/assets/144561200/131f1c93-b8f4-4b96-9d88-65ea45edbb32)

And the console, show the attached error for the properties.
![image](https://github.com/IFCjs/components/assets/144561200/ef49b5ae-b8e2-456e-b341-faa6adabdbd5)

Testing IFC Model (Zipped for upload):
[XXXX_AARR.zip](https://github.com/IFCjs/components/files/12723983/XXXX_AARR.zip)

### System Info 💻

```shell
Fedora Linux 38
AMD Ryzen 5 5625U with Radeon™ Graphics × 12
16 GBRAM
React + Vite
openbim-componentes 1.1.0
```

### Used Package Manager 📦

npm

### Error Trace/Logs 📃

index.ts:146 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'value')
    at _IfcPropertiesUtils.getEntityName (index.ts:146:37)
    at _IfcPropertiesProcessor.newEntityTree (index.ts:462:41)
    at _IfcPropertiesProcessor.newEntityUI (index.ts:294:28)
    at _IfcPropertiesProcessor.renderProperties (index.ts:268:21)

### Validations ✅

- [X] Read the [docs](https://platform.thatopen.com/documentation).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a IFC.js components issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by beachtom** [comment]
I think this is now fixed at least the rendering elements - can you please re-open if not the case
