### ISSUE TITLE
[Bug]: Incorrect slab geometry in v 0.0.44

### ISSUE THREAD

**Issue by ENG-Mazri** [ThatOpen/engine_web-ifc#525]
### What happened?

Slab geometry looks like this in v0.0.44:
![slab](https://github.com/IFCjs/web-ifc/assets/84850871/64657d36-a666-4116-a68e-790bd9d30615)

in v0.039 it looked the right way:
![slab39](https://github.com/IFCjs/web-ifc/assets/84850871/60fbd58d-12b5-4992-a6ea-0351533d45a8)

another example from v 0.0.44
![slab2](https://github.com/IFCjs/web-ifc/assets/84850871/c5b0f073-53ee-4aed-8476-e6ac20cf29e5)

### Version

0.0.44

**Comment by CodeVijay53** [comment]
Could you please let me know in which version and browser do you see this problem.

**Comment by QuimMoya** [comment]
Can you share the model?

**Comment by ENG-Mazri** [comment]
> Can you share the model?

actually this was fixed in the 0.0.51 version :)
