### ISSUE TITLE
[Bug]: 15Mo IFC file takes more than 5 minutes to load

### ISSUE THREAD

**Issue by TristanLecallier** [ThatOpen/engine_web-ifc#527]
### What happened?

Parsing a 15 mo ifc file takes more than 5 minutes to load.
Data is confidential so I sent the ifc file to @A

### Version

0.0.44

### What browsers are you seeing the problem on?

Chrome

**Comment by QuimMoya** [comment]
I think you will have to send it again. We can't find the file.

**Comment by agviegas** [comment]
@QuimMoya file privately available [here](https://drive.google.com/file/d/1vji468WuMvOmhQa7i1WbE_nN8htCbjCj/view?usp=drive_link).

**Comment by QuimMoya** [comment]
![image](https://github.com/user-attachments/assets/6bed2548-389c-471d-84bc-8ed5a6b2c4a3)
The latest commits open the 10 MB model. Test it in [Demo](https://thatopen.github.io/engine_web-ifc/demo)

The other model can be opened with a special update I'm testing.
![image](https://github.com/user-attachments/assets/34d27807-ea97-45fb-9c49-d88231b95e96)
