### ISSUE TITLE
Rebar radius wrong direction

### ISSUE THREAD

**Issue by gjordanp** [ThatOpen/engine_web-ifc#529]
### Describe the bug 📝

I'm loading ifc models in IFCjs demo and on the Open viewer https://platform.thatopen.com/app.

I notice that rebar radius is wrong in the model making weird shapes.

That Open Viewer:
![image](https://github.com/IFCjs/components/assets/67670790/50ee7b95-2491-4399-b53b-da7f3bbaa2f4)

IFCjs Viewer:
![image](https://github.com/IFCjs/components/assets/67670790/ee727921-72b6-4f31-9046-39d51044acca)

Revit:
![image](https://github.com/IFCjs/components/assets/67670790/fc9ea90b-7425-4b44-92c7-6e98fb848d6b)

### Reproduction ▶️

https://spoerering-my.sharepoint.com/:u:/g/personal/gjordan_btd_cl/EdwsR5y7QzxFr0PVX32QOp4BQ9f4RPfr6qqftfIkcp08nA?e=aJR0xn

### Steps to reproduce 🔢

1. Download IFC model from link.
2. Load IFC on https://platform.thatopen.com/app
3.  Load IFC on https://ifcjs.github.io/web-ifc-viewer/example/index

### System Info 💻

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (24) x64 12th Gen Intel(R) Core(TM) i9-12900K
    Memory: 15.71 GB / 31.75 GB
  Binaries:
    Node: 19.8.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.15.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.2283.0), Chromium (117.0.2045.41)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://platform.thatopen.com/documentation).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a IFC.js components issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by QuimMoya** [comment]
We have a possible solution, but i have to test it.

![image](https://github.com/ThatOpen/engine_web-ifc/assets/12625508/95c1a401-8132-4690-87c6-f251375ec409)

**Comment by QuimMoya** [comment]
![image](https://github.com/user-attachments/assets/240b6680-805d-4a73-8664-7d23513b2d49)


The issue seems to be fixed now

**Comment by gjordanp** [comment]
> ![image](https://private-user-images.githubusercontent.com/12625508/373190967-240b6680-805d-4a73-8664-7d23513b2d49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NjA5OTIsIm5iZiI6MTcyNzk2MDY5MiwicGF0aCI6Ii8xMjYyNTUwOC8zNzMxOTA5NjctMjQwYjY2ODAtODA1ZC00YTczLTg2NjQtN2QyMzUxM2IyZDQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDEzMDQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3MzRiYjMyMDYxNDg3NDVlNGI5MzM0OWIzMjIyOTlhMWU5ZTUxZTFhMDFhZjk0OWRlNGFkMmE5MGU4YjhiNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ktJutogMDFODcVbghASi-DN-ze6FwN5Vtc-aYcdyjQI)
> 
> The issue seems to be fixed now

Thanks!!
