### ISSUE TITLE
IFC Geometry not converted correctly into Threejs meshes

### ISSUE THREAD

**Issue by Alex-Schlachter27** [ThatOpen/engine_web-ifc#546]
### Describe the bug 📝

In my ifc-model from Tekla, some curved elements are not converted correctly. Please see the following picture from the thatopen-showcase-app. 

![image](https://github.com/IFCjs/fragment/assets/62239809/a1f03d10-5cb0-4729-aa6f-0b20a2da32c1)
![image](https://github.com/IFCjs/fragment/assets/62239809/6025b3d7-3d65-4c26-bbe6-cc812d98f075)

In a slightly older app, I develoepd with web-ifc-three, most of the geometries look good. Is this because you use another version for converting the ifc-geometries? 
Some geometries, however, are still not converted correctly. 
![image](https://github.com/IFCjs/fragment/assets/62239809/35348ebf-f675-4315-a503-c45043246793)

Here is an example from Trimble Connect how it should look like. 
![image](https://github.com/IFCjs/fragment/assets/62239809/59d588d5-af7c-4935-9912-2be253fb1df7)

With the following link, you can download the model:
https://dl.dropboxusercontent.com/s/0hrq6lerkhfpl6i/CR-AAR-GEN%3DNEL6-CP%3DPRI%3DGEN-CST-MEX-0001-%5E-%5E_4D.ifc?dl=0

### Reproduction ▶️

https://dl.dropboxusercontent.com/s/0hrq6lerkhfpl6i/CR-AAR-GEN%3DNEL6-CP%3DPRI%3DGEN-CST-MEX-0001-%5E-%5E_4D.ifc?dl=0

### System Info 💻

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 Intel(R) Xeon(R) W-11955M CPU @ 2.60GHz
    Memory: 30.71 GB / 63.67 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (120.0.2210.121)
    Internet Explorer: 11.0.19041.3636
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/fragment/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by QuimMoya** [comment]
Solved, but i have to check other models.

It was caused by units:

![image](https://github.com/ThatOpen/engine_web-ifc/assets/12625508/06fe5032-8f79-4c9f-8031-2471a5537ea3)
