### ISSUE TITLE
Incorrect shape of holes

### ISSUE THREAD

**Issue by robertbiskup** [ThatOpen/engine_web-ifc#573]
### Describe the bug 📝

![image](https://github.com/IFCjs/components/assets/87365468/268d9578-88c0-45b5-b762-6d450d8569ca)
![image](https://github.com/IFCjs/components/assets/87365468/af2fc026-82a3-4806-8a09-c8d2649613cb)

[HolesIssue.zip](https://github.com/IFCjs/components/files/13634828/HolesIssue.zip)
 
Loaded ifc has incorrect holes - its should be rounded as shown on screen from BIMVision.

### Steps to reproduce 🔢

Load attached ifc file

### System Info 💻

```shell
"openbim-components": "1.2.0"
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by robertbiskup** [comment]
Hi, @beachtom, is there a chance to check this issue and perhaps solve it?

**Comment by QuimMoya** [comment]
I'm working on it.

**Comment by QuimMoya** [comment]
![image](https://github.com/user-attachments/assets/c41e69cf-6167-493f-8e93-29c4efea41f5)
Solved, i will commit it today. Tomorrow you can test it with [https://thatopen.github.io/engine_web-ifc/demo/](https://thatopen.github.io/engine_web-ifc/demo/)
