### ISSUE TITLE
[Bug]: Missing geometry, while stream all meshes

### ISSUE THREAD

**Issue by rkaeplive** [ThatOpen/engine_web-ifc#590]
### What happened?

hello! Missing some geometry, while stream all meshes with web-ifc-api
<img width="677" alt="image" src="https://github.com/IFCjs/web-ifc/assets/80881455/620ac936-121c-45e2-841b-da08cec281ad">
<img width="471" alt="image" src="https://github.com/IFCjs/web-ifc/assets/80881455/172cd068-3da9-4f6d-a69d-b394cf723ab8">
 
The vertex and index arrays is empty 
<img width="479" alt="image" src="https://github.com/IFCjs/web-ifc/assets/80881455/c10ff361-375f-4862-98d8-5fbde8cd190f">

log: Float32Array(0) [] Uint32Array(0) [] 8395

### Version

0.0.47

**Comment by rkaeplive** [comment]
Error with IfcBooleanClippingResult 
<img width="426" alt="image" src="https://github.com/IFCjs/web-ifc/assets/80881455/23e8b75b-fc94-4bde-95a3-2e39d12c5cb7">

**Comment by rkaeplive** [comment]
[Uploading 1110-PR117I-A.IFC.zip…]()

**Comment by rkaeplive** [comment]
[1110-PR117I-A.IFC.zip](https://github.com/IFCjs/web-ifc/files/14161883/1110-PR117I-A.IFC.zip)

**Comment by rkaeplive** [comment]
Hello?

**Comment by rkaeplive** [comment]
@beachtom  Hello, can you help with this issues ? Its not solved in new update

**Comment by QuimMoya** [comment]
![image](https://github.com/ThatOpen/engine_web-ifc/assets/12625508/9ca7d26e-4a59-476a-953a-a566ae04685e)
This?

**Comment by rkaeplive** [comment]
> ![image](https://private-user-images.githubusercontent.com/12625508/313142172-9ca7d26e-4a59-476a-953a-a566ae04685e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1MDk1ODEsIm5iZiI6MTcxMDUwOTI4MSwicGF0aCI6Ii8xMjYyNTUwOC8zMTMxNDIxNzItOWNhN2QyNmUtNGE1OS00NzZhLTk1M2EtYTU2NmFlMDQ2ODVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDEzMjgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkM2UzNDQwYWFkYWZmYjg3N2U3NmI2YzMwZDU3NDkwYzM3YzM1Mjk0ZWVjNWYzYWNjYjBjNDdlZTJlYzNmMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.04wk2JGuNQ0F5_N_vxwWUuDb_lepCJtdBKPVR8f19oc) This? Solved with the last commit. There were missing lines of code in T profiles

Yes!!! Thank you very much!
