### ISSUE TITLE
[Bug]: Model freezes (probably to bool operations)

### ISSUE THREAD

**Issue by agviegas** [ThatOpen/engine_web-ifc#604]
### What happened?

The loading of the model freezes. The model can be found [here](https://drive.google.com/file/d/1HW4vsxA3QU-dAkVc_VgVzXro1IB3TnmX/view?usp=drive_link).

### Version

0.0.50

**Comment by QuimMoya** [comment]
![image](https://github.com/ThatOpen/engine_web-ifc/assets/12625508/8ec2887a-f6be-4774-8435-313f9449c477)

Now open in 1-2 minutes

**Comment by beachtom** [comment]
Closing this as the model now opens fine
