### ISSUE TITLE
[Bug]: Regression Writing "Integer" Values with writeRawLineData, superflous wrapping in ToRawLineData causes wrong value to be written

### ISSUE THREAD

**Issue by quasarchimaere** [ThatOpen/engine_web-ifc#650]
### What happened?

Using ToRawLineData, seems to have a regression of sorts since the output
`
- #664=IFCOWNERHISTORY(#661,#663,$,.MODIFIED.,1600,#661,#663,1600);
+ #664=IFCOWNERHISTORY(#661,#663,$,.MODIFIED.,-2147483648,#661,#663,-2147483648);
`

According to the package diff (seen in https://diff.intrinsic.com/web-ifc/0.0.46/0.0.51 ) there is an Issue with the `ToRawLineData` functions, `{type: 10, value: [val]}` is wrapped around the parameter, and since the parameter itself encapsulates an `IfcTimeStamp` it unnecessarily puts an object where a sole value should be used.

Warn: This does not only affect the IfcOwnerHistory but basically every Line that is written and uses an Integer value, and instead writes the `-2147483648` as the Integer (which is basically all 1's in 32 bit afaik)

`
-  1207048766: (i) => [i.OwningUser, i.OwningApplication, i.State, i.ChangeAction, i.LastModifiedDate, i.LastModifyingUser, i.LastModifyingApplication, i.CreationDate],
+  1207048766: (i) => [i.OwningUser, i.OwningApplication, i.State, i.ChangeAction, i.LastModifiedDate == null ? null : { type: 10, value: i.LastModifiedDate }, i.LastModifyingUser, i.LastModifyingApplication, { type: 10, value: i.CreationDate }],
`

### Version

0.0.51

### Anything else?

As far as i am concerned this was introduced with commit https://github.com/ThatOpen/engine_web-ifc/commit/73c4275b2e3c94fe0e86321b6376045842633ea5 which tried to fix issue https://github.com/ThatOpen/engine_web-ifc/issues/534

The "Fix" introduced the wrapping of the Parameter object
`
[...]
else if (type?.typeNum == 10 || p.typeNum==10) 
    {
        let response:string = "";
        if (p.optional) response +=`i.${p.name} == null ? null : `;
        response += `{type:10,value:i.${p.name}}`; // <-- ** I think that ${p.name} should actually be ${p.name}.value
        return response;
    }
    if (p.name=="Exponent") console.log(p);
    return `i.${p.name}`;
`

**Comment by quasarchimaere** [comment]
@beachtom it might be that the issue fix introduced in the  https://github.com/ThatOpen/engine_web-ifc/issues/534 was not even necessary, and the Exponent issue was solely on our end, since we created Exponents as Number and not Integer types.

**Comment by beachtom** [comment]
OK let me look into this.

**Comment by quasarchimaere** [comment]
@beachtom Further Info: yes, my assumption was correct. there was actually no exponent issue while writing IFCDERIVEDUNITELEMENT in the first place, we simply parsed the wrong type (type: 4) into the rawLineData and thus it was written as a real value instead of an integer, switching our unitgeneration to ints (type: 10) fixes the issue within web-ifc 0.0.50 (which was the version before your fix got committed), so i assume that removing the wrapping `{type: 10, value: [i.something]}`  is unnecessary and can be removed again.

**Comment by beachtom** [comment]
I've rolled this back. So hopefully it work now.
