### ISSUE TITLE
[Suggestion]: Can you or whoever implements fixes and features refer to the fixed issue in the commit message please?

### ISSUE THREAD

**Issue by quasarchimaere** [ThatOpen/engine_web-ifc#651]
### What is your idea?

i don't know, i am not asking for implementing a git commit message structure or some sort of linting, but it would be VERY beneficial if you could at least write the issue number of the fix in the commit message, otherwise trying to retrace changes made can be super tedious, (e.g. you have to see that an issue is commented as fixed, then find out when the fix happened and check the commits around that time and maybe you figure out which commit was the actual fix)

just a suggestion

**Comment by beachtom** [comment]
Thanks - will note this!
