### ISSUE TITLE
[Bug]: IFCINTEGER limited to 2^31 (A 32-bit signed integer)

### ISSUE THREAD

**Issue by ragnhmyr** [ThatOpen/engine_web-ifc#658]
### What happened?

Hi!

We have an ifc model with a property value of ``IFCINTEGER(-2147483649)``
which fails if the number is below -2147483648 (2^31)
BIM viewers like BIM Collab ZOOM can read the model with no problems

The method that fails is 
``IfcApi.getLine(modelId,60)`` 

where the line in the ifc is like:

``#60= IFCPROPERTYSINGLEVALUE('FingerPrint',$,IFCINTEGER(-2147483649),$);``

-2147483648 (2^31) works
<= -2147483649 does not work 

Assuming that it is due to IFCINTEGER being limited to a 32-bit signed integer

### Version

0.0.49

### Relevant log output

```shell
stoi: out of range
```

**Comment by beachtom** [comment]
Closed as fixed
