### ISSUE TITLE
[Bug]: Something is wrong geometry in version 0.0.51  

### ISSUE THREAD

**Issue by RyugaRyuzaki** [ThatOpen/engine_web-ifc#664]
### What happened?

There is a difference between the two versions web-ifc@0.0.51 vs web-ifc@0.0.46. Road as of version 0.0.51 some geometry is displayed incorrectly. Here are the differences 
![V0 0 51](https://github.com/ThatOpen/engine_web-ifc/assets/89787521/0db0a9e1-f70a-4455-89e3-d54ce1fba362)
![V0 0 46](https://github.com/ThatOpen/engine_web-ifc/assets/89787521/48359b47-b3fe-45e0-9185-23388b37e63d)

### Version

web-ifc@0.0.51

**Comment by rkaeplive** [comment]
@beachtom 
Hello, I have same issues with many models, please, fix it!!!

**Comment by beachtom** [comment]
Can you share some images/models Can you also confirm which was the last "good version" is it 0.46? Can you try 0.47/48/49/50 please?

**Comment by RyugaRyuzaki** [comment]
hi @beachtom to be carefull i will test with 2 files. This appears from version @0.0.51, with others older was fine.
- Version 0.0.50 
- ![web-ifc@0 0 50-file1](https://github.com/ThatOpen/engine_web-ifc/assets/89787521/7258648f-d651-4615-8045-ee742771ccf5)
- ![web-ifc@0 0 50-file2](https://github.com/ThatOpen/engine_web-ifc/assets/89787521/f6a15187-354e-4269-aeee-49a49cb3b3da)
- Version 0.0.51 
- ![web-ifc@0 0 51-file1](https://github.com/ThatOpen/engine_web-ifc/assets/89787521/31a1b554-ef1c-4305-bf9e-755b70846ff6)
- ![web-ifc@0 0 51-file2](https://github.com/ThatOpen/engine_web-ifc/assets/89787521/841a1af5-897a-4410-a788-de6a0a76b391)

**Comment by beachtom** [comment]
Thanks!

**Comment by rkaeplive** [comment]
@beachtom 
hello, you can see another example here
https://github.com/ThatOpen/engine_web-ifc/issues/597

**Comment by rkaeplive** [comment]
> Are you able to share any of the models - it will make debugging much quicker

https://github.com/ThatOpen/engine_web-ifc/issues/597
