### ISSUE TITLE
Web-IFC on Next.js

### ISSUE THREAD

**Issue by SoftwareMechanic** [ThatOpen/engine_web-ifc#670]
### What happened?

Hello!
I am trying to make a simple runtime geometry generator with data to assign to geometries and exporter.
I would like to use Next.js, but it's not very clear to me how I should proceed.
Once I installed web-ifc I am creating the following component in order to try to import an IFC file:

```
import { useEffect, useRef } from "react";
//import { IfcAPI } from 'web-ifc';


const IfcGenerator = () => {
    const ifcAPI = useRef(null);
    const modelID = useRef(null);

    useEffect(() => {
        const init = async () => {
            //const WebIFC = require("web-ifc/web-ifc-api.js");
            const { IfcAPI } = await import('web-ifc');
            ifcAPI.current = new IfcAPI();
            await ifcAPI.current.Init();
            console.log("ifc api initialized");
        };
        init();
    }, []);

    const handleFileChange = async (event) => {
        const file = event.target.files[0];
        const fileBuffer = await file.arrayBuffer();
        modelID.current = ifcAPI.current.OpenModel(new Uint8Array(fileBuffer));
        console.log("Model opened with ID:", modelID.current);
    };

    return (
        <div>
            <input type="file" onChange={handleFileChange} />
        </div>
    );
};

export default IfcGenerator;

```

### Version

"^0.0.36"

### What browsers are you seeing the problem on?

Firefox, Chrome

### Relevant log output

```shell
abort(both async and sync fetching of the wasm failed).
```

### Anything else?

Next.js 12

**Comment by beachtom** [comment]
I am not familir with react - but I would expect you need the import at the top of the file not in the function. The error is probably to do with bundling. You need to make sure the wasm is available in a public directory or similar so it can be fetched by the javascript.

**Comment by SoftwareMechanic** [comment]
Thank you for the answer! 
I tried importing it in different ways, but the problem is not the import, the problem is when I try to initialize it `Init()` 
even if I call the method SetWasmPath before, with both relative or absolute path. 
😢

**Comment by beachtom** [comment]
Can you look at the developer tools in the log and see what is happening when it tries to retrieve the wasm? If you can show me I can help from there

**Comment by beachtom** [comment]
Is the file actually there - can you access it in the browser? It is something to do with your bundling - you may need to explicit tell the bunlder to put the wasm file in there.

**Comment by SoftwareMechanic** [comment]
if I type the path in the browser, the browser downloads it for me: 
![immagine](https://github.com/ThatOpen/engine_web-ifc/assets/53627894/2c8a26dc-4e29-4f10-889f-3581d3d9da6d)

I will search for more info on how to bundle it.

**Comment by beachtom** [comment]
yeah that is part of the normal process - you need to add, either as part of the build or bundling, the wasm file.

I think this is the normal approach to take.

you can change the wasm path SetWasmPath('../../../')
