### ISSUE TITLE
[Feat]: Create IFC directly from Threejs meshes (e.g. THREE.BoxGeometry)?

### ISSUE THREAD

**Issue by dirkarnez** [ThatOpen/engine_web-ifc#683]
### What is your idea?

May i ask is it a working feature, please? I see https://github.com/ThatOpen/web-ifc-three/commit/cb4d9ab23ce941478ed43270ae0b1b73d28ed9cc is working on the idea, may i know if you guys are going to support arbitrary geometry / merged geometry, please? I am very interesting in this topic, would like to help with this topic if needed!

**Comment by agviegas** [comment]
Indeed, this is going to be a feature for [clay](https://github.com/ThatOpen/engine_clay). We already have it working for some elements. This is WIP and will be released this summer.

**Comment by dirkarnez** [comment]
> Indeed, this is going to be a feature for [clay](https://github.com/ThatOpen/engine_clay). We already have it working for some elements. This is WIP and will be released this summer.

WOW that is amazing!
