### ISSUE TITLE
[Bug]: Colors not displaying correctly

### ISSUE THREAD

**Issue by agviegas** [ThatOpen/engine_web-ifc#722]
### What happened?

With [this model](https://drive.google.com/file/d/1TikReZpDEJiNuHj7cALNjQiROg9NZdFa/view?usp=drive_link), all colors are black. In other viewers they display correctly.

### Version

0.0.51

### What browsers are you seeing the problem on?

Chrome

**Comment by QuimMoya** [comment]
I think it is solved

![image](https://github.com/ThatOpen/engine_web-ifc/assets/12625508/b9bfda6a-d20e-46c9-91a0-71d295d4a765)

**Comment by agviegas** [comment]
In the latest version of BIM vision this looks like this. There seems to be something wrong with the colors yet!

![image](https://github.com/ThatOpen/engine_web-ifc/assets/56475338/7541ea9b-4839-46c7-a121-e31e5bce17db)

**Comment by beachtom** [comment]
Properly fixed now!
