### ISSUE TITLE
[Bug]: 404 at ifcjs.github.io/web-ifc/demo/

### ISSUE THREAD

**Issue by prideout** [ThatOpen/engine_web-ifc#733]
### What happened?

This link is advertised on the main repo page, but it is a 404.

### Version

1.0

**Comment by beachtom** [comment]
Hi, can you identify where it is - i thought I changed them all

**Comment by prideout** [comment]
The URL is shown in the "About" section of the main repo page (top right corner) at https://github.com/ThatOpen/engine_web-ifc

**Comment by ismail-codar** [comment]
![image](https://github.com/ThatOpen/engine_web-ifc/assets/282104/dfaeb31b-151c-45ec-b7ce-aa03520420b4)

**Comment by beachtom** [comment]
Thanks this is fixed
