### ISSUE TITLE
[Bug]: IfcBoolean value is written as '.true.'  instead of '.T.'

### ISSUE THREAD

**Issue by NiklasPor** [ThatOpen/engine_web-ifc#740]
### What happened?

If you use the IfcBoolean API like it's intended, it will output an incorrect file.

Using the constructor like this `new IfcBoolean('T')` will lead to an object with `{ value: true }` and this will print the IFC lines like this: `IFCBOOLEAN(.true.)`, which is an incorrect ifc line.

Workaround: Ignore that the typing of `value` is boolean and do the following:
```ts
const myBool = new IfcBoolean(undefined):
myBool.value = 'T' as any;
```

We either need to remove the internal conversion and just allow `'T' | 'F' | 'U'` as values, or we need to add an additional conversion step when writing the `IfcBoolean` as a step file line.

### Version

0.0.51

### What browsers are you seeing the problem on?

Chrome

**Comment by beachtom** [comment]
I thought this was fixed - is it a regression you've noticed in 0.51 or has it always been broken?

**Comment by NiklasPor** [comment]
Noticed this in `0.50.` and checked in `0.51` to see if the update was gonna fix it. I tried to find where the code in this repo for the `IfcBoolean` was, but I didn't manage to find anything relevant to writing out the value of it.

In which version of web-ifc should it have been fixed?

**Comment by beachtom** [comment]
Should now be fixed properly!
