### ISSUE TITLE
[Bug]: Something still went wrong geometry with version @0.0.51 ,

### ISSUE THREAD

**Issue by RyugaRyuzaki** [ThatOpen/engine_web-ifc#742]
### What happened?

Something still went wrong geometry with version @0.0.51 but with old version not
 - version <=@0.0.50 
![image](https://github.com/ThatOpen/engine_web-ifc/assets/89787521/e29e30e0-2d92-4f12-a31d-b87de20fcea9)
- verion @0.0.51 
![image](https://github.com/ThatOpen/engine_web-ifc/assets/89787521/567ddf50-5d83-4b99-b549-bfa5c0ac338b)

### Version

web-ifc@0.0.51

**Comment by beachtom** [comment]
Can you try the model on the demo from this repo? Or share it with me? Happy for sharing privately.

**Comment by beachtom** [comment]
So this is now fixed -I do not the issues in your other issue and will try to resolve them
