### ISSUE TITLE
[Bug]: It does not load IFCMEMBERS from an IFCCURTAINWALL

### ISSUE THREAD

**Issue by jespa007** [ThatOpen/engine_web-ifc#750]
### What happened?

engine_web-ifc demo (i.e https://thatopen.github.io/engine_web-ifc/demo/) does not load IFCMEMBERS from an IFC with an IFCCURTAINWALL. The file which is causing the issue is attached below,

[Parent_Child.zip](https://github.com/ThatOpen/engine_web-ifc/files/14874363/Parent_Child.zip)

Rendered image,

![image](https://github.com/ThatOpen/engine_web-ifc/assets/7852409/85a9f466-8424-414f-841a-4588100abd51)

### Version

last version

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
In the console show the following error,

Uncaught (in promise) TypeError: (void 0) is not a function
    at IfcThree.LoadAllGeometry (web-ifc-viewer.js:267594:46)
    at LoadModel (web-ifc-viewer.js:269100:12)
    at reader.onload (web-ifc-viewer.js:269083:5)
```

### Anything else?

I have already attached the IFC in this issue

**Comment by quasarchimaere** [comment]
not sure if this is relevant, but according to your log output you are still using IfcThree and web-ifc-viewer, which isnt really maintained anymore, you should try using web-ifc with openbim-components first, look at the guidance/tutorials around thatopen.com

**Comment by jespa007** [comment]
> not sure if this is relevant, but according to your log output you are still using IfcThree and web-ifc-viewer, which isnt really maintained anymore, you should try using web-ifc with openbim-components first, look at the guidance/tutorials around thatopen.com

Hi @quasarchimaere,
The output of the error comes from the engine_web-ifc demo that it has itself engine_web-ifc page (i.e https://thatopen.github.io/engine_web-ifc/demo/) that it suposes is the last version. And I already know that web-ifc-three and web-ifc-viewer is already deprecated and not used anymore. Of course, I would have  put the issue in the other repository if the issue is related to web-ifc-three.

**Comment by quasarchimaere** [comment]
@jespa007 apologies

**Comment by beachtom** [comment]
So from what I can tell it seems to work.  The output I get matches what I get in several other viewers.... can you clarify what it should look like if this is not right

<img width="384" alt="Screenshot 2024-04-13 at 12 47 42" src="https://github.com/ThatOpen/engine_web-ifc/assets/26248350/50c62e17-64e8-4acc-b333-c3f6eccc9502">

**Comment by jespa007** [comment]
thanks @beachtom
