### ISSUE TITLE
[Bug]: Some geometry went wrong with versions @0.0.51, @0.0.52 and @0.0.53 with older versions is fine

### ISSUE THREAD

**Issue by RyugaRyuzaki** [ThatOpen/engine_web-ifc#754]
### What happened?

A bug happened!

- @0.0.50 
![image](https://github.com/ThatOpen/engine_web-ifc/assets/89787521/19af9a61-3dc0-42ba-98c1-89446606e9c8)
![image](https://github.com/ThatOpen/engine_web-ifc/assets/89787521/f33a5a10-054e-4481-b618-afffdef37bae)

- @0.0.51 
![image](https://github.com/ThatOpen/engine_web-ifc/assets/89787521/a1523f0c-f2c1-4c25-8ed2-29d7a51375d4)
![image](https://github.com/ThatOpen/engine_web-ifc/assets/89787521/5e93698c-30f2-49e4-95f9-053fef6982d1)
![image](https://github.com/ThatOpen/engine_web-ifc/assets/89787521/91f07f4a-5fd8-49d5-b060-3ac1c6ad1e37)

- @0.0.52
![image](https://github.com/ThatOpen/engine_web-ifc/assets/89787521/45e3b5a2-a82e-4775-9588-f5a3acd6b454)
![image](https://github.com/ThatOpen/engine_web-ifc/assets/89787521/21646629-3c9f-485e-b1db-bd4484130bfc)
![image](https://github.com/ThatOpen/engine_web-ifc/assets/89787521/32ac21bd-2db4-418d-9011-dbaabe0511c4)

- @0.0.53 
![image](https://github.com/ThatOpen/engine_web-ifc/assets/89787521/411846ec-73d8-4fc3-8ea2-232479691b92)
![image](https://github.com/ThatOpen/engine_web-ifc/assets/89787521/a23b1b1b-8fb6-41e9-a22f-549dcc003a2a)
![image](https://github.com/ThatOpen/engine_web-ifc/assets/89787521/f43af4de-7c61-4352-94f1-3f68d514a907)

- These are 2 files i tested 
- https://drive.google.com/file/d/175L2PuXtxXX4Nit35hM6QT8rrGrYc43i/view?usp=sharing
- https://drive.google.com/file/d/1-0yaVh03acNRSNz0vGHk9E5Ys_G9IjYO/view?usp=sharing

### Version

@0.0.51, @0.0.52 and @0.0.53

**Comment by eng-luciano-julien** [comment]
I have this problem too with my models.
I am using FragmentStreamLoader on the frontend.

**Comment by eng-luciano-julien** [comment]
I was using @0.0.51, changing to @0.0.50 solved the problem

**Comment by rkaeplive** [comment]
I have too
https://github.com/ThatOpen/engine_web-ifc/issues/791

**Comment by beachtom** [comment]
The alignment seems to be fixed now - but another issue has developed with Windows
