### ISSUE TITLE
[Bug]: 2 Closed Issues are still present in web-ifc 0.0.53 (as far as i know it is not a regression, because it never worked to begin with)

### ISSUE THREAD

**Issue by quasarchimaere** [ThatOpen/engine_web-ifc#760]
### What happened?

I can't reopen Issues here, and even though i made comments within the closed issues, idk if they are currently being handled, hence why i created this issue to raise awareness that the following two bugs, are still present in the latest version of ifc js

- https://github.com/ThatOpen/engine_web-ifc/issues/636
- https://github.com/ThatOpen/engine_web-ifc/issues/498

### Version

0.0.53

**Comment by beachtom** [comment]
Closing this to continue discussion on other issues
