### ISSUE TITLE
[Bug]: Profile error

### ISSUE THREAD

**Issue by agviegas** [ThatOpen/engine_web-ifc#765]
### What happened?

[Small model](https://drive.google.com/file/d/1dCSNLORJzpFE0LAmPrfRj3t4rrTCcuLU/view?usp=drive_link), but not displaying correctly. 

web-ifc:
![image](https://github.com/ThatOpen/engine_web-ifc/assets/56475338/b3ac2895-d86a-4746-98c1-cb94501475e2)

navis:
![image](https://github.com/ThatOpen/engine_web-ifc/assets/56475338/2f475bf4-e3fa-4c10-888b-2db61af252f6)

### Version

0.0.53

### What browsers are you seeing the problem on?

Chrome

**Comment by QuimMoya** [comment]
Solved

![image](https://github.com/ThatOpen/engine_web-ifc/assets/12625508/255b3ed9-5bb5-4ef3-ab7d-f457ddb23681)

**Comment by jimbosquash** [comment]
only seeing this now but greatly appreciate your fix here! will be making a new bug for another geometry issue found. kind regards, J
