### ISSUE TITLE
[Bug]: Error with geometry and miss some of them 

### ISSUE THREAD

**Issue by rkaeplive** [ThatOpen/engine_web-ifc#791]
### What happened?

Hello! In any models where are bug with geometry and some geometry - missed
Bim Collab:
<img width="1052" alt="image" src="https://github.com/ThatOpen/engine_web-ifc/assets/80881455/bd79d8e6-2532-4101-b3fc-c9f8a381a031">
Web-ifc:
<img width="817" alt="image" src="https://github.com/ThatOpen/engine_web-ifc/assets/80881455/a1b2dee8-3ba4-4dd1-bc7a-97c4e32b2499">
Ifc file: 
[test.ifc.zip](https://github.com/ThatOpen/engine_web-ifc/files/15128111/test.ifc.zip)

### Version

0.0.54

### What browsers are you seeing the problem on?

Chrome, Safari

**Comment by Felipemore96** [comment]
Hello! Please share the model to check what's the issue

**Comment by QuimMoya** [comment]
![image](https://github.com/user-attachments/assets/84bf3b3a-bf04-4ce5-9c26-7b71f176504d)
It is solved now
