### ISSUE TITLE
Add new IFC element at specific co-ordinate in the loaded 3D view

### ISSUE THREAD

**Issue by vishalpatil3390** [ThatOpen/engine_web-ifc#797]
### What is your idea?

Is it possible to add new IFC element such as chair or device at specific co-ordinate in the loaded 3D view

**Comment by beachtom** [comment]
Technically yes - but web-ifc is a low level library so you would need to construct the IFC lines and the geometry yourself manually. That is probably not what you want. I know there is work going on about the clay library that will do this - but it is not ready yet.
