### ISSUE TITLE
[Bug]: error with geometry of basic model

### ISSUE THREAD

**Issue by rkaeplive** [ThatOpen/engine_web-ifc#810]
### What happened?

Hello, one more bug happened in new version of web-ifc
<img width="1448" alt="image" src="https://github.com/ThatOpen/engine_web-ifc/assets/80881455/ca88b09b-ca7f-45d1-8c8e-fd7e920b3256">
[Clinic_Architectural.ifc.zip](https://github.com/ThatOpen/engine_web-ifc/files/15247243/Clinic_Architectural.ifc.zip)

### Version

0.0.54

**Comment by rkaeplive** [comment]
Hello, @beachtom please fix it

**Comment by beachtom** [comment]
@rkaeplive I think this is fixed now. Please re-open if not!
