### ISSUE TITLE
[Bug]: IFC Model Alignment Issue

### ISSUE THREAD

**Issue by Issa369** [ThatOpen/engine_web-ifc#812]
### What happened?

I'm currently encountering an issue while streaming some IFC files. I was testing a 1.2 GB file and noticed that some walls were not being rendered due to their vertex arrays being empty, which results in a null bounding box. Interestingly, a very similar wall works perfectly. I found a related issue https://github.com/ThatOpen/engine_web-ifc/issues/590 with someone else's file, tested their fix by updating web-ifc along with the wasm files, and it resolved the issue for that file. However, when I applied the same update to my file, it unfortunately didn't work.

Additionally, I thought that updating openbim-components and web-ifc along with their respective modules might help, but while this update did resolve the issue, it caused the elements in my model to misalign, even though other models work perfectly with these updates.

Any insights or suggestions would be greatly appreciated!
![329885697-4c0a4f4b-8cca-4866-9113-8ad8c832b904](https://github.com/ThatOpen/engine_web-ifc/assets/114977591/eb89e703-c286-4f14-902a-864a9d27851f)

### Version

0.0.53

### What browsers are you seeing the problem on?

Chrome

**Comment by beachtom** [comment]
Can you check this with the latest demo https://thatopen.github.io/engine_web-ifc/demo/ and see if is fixed - or if you can share the model I will take a look

**Comment by Issa369** [comment]
well the problem escalated actually, its more complicated now, the problem was with the library it self with the web-ifc or the wasm files, but they are fixed now. the problem now is that there is missing geometries in the web-ifc it self, i will be attaching the ifc file that has the missing geometry, try viewing it with bimvision a
[21.txt](https://github.com/ThatOpen/engine_web-ifc/files/15422641/21.txt)
nd then check it on the ifc viewer itself. I wanted to make a new issue for this because its a separate problem with web-ifc but i didn't have the time.
Please check out the attached ifc file to know what is the problem, also change the format of that file to ifc cause i couldn't upload it here, thanks!

**Comment by beachtom** [comment]
OK - I think someone is looking at the other issues - but can you check if the alignments are fixed? Or are they in this model?

**Comment by Issa369** [comment]
Yes, the alignment issue is fixed i tested it, now the problem is with [THIS](https://github.com/ThatOpen/engine_web-ifc/issues/830)  i made an issue for the thing i talked about

**Comment by beachtom** [comment]
Fab I am going to close this just to keep track - and we will keep working on the other issue
