### ISSUE TITLE
[Bug]: Model processing results in Aborted()

### ISSUE THREAD

**Issue by hellghostx** [ThatOpen/engine_web-ifc#818]
### What happened?

During model processing there is an abort with this error message. Same behaviour tested on your demo viewer.

![obrazek](https://github.com/ThatOpen/engine_web-ifc/assets/26725817/e2416a31-33d3-422c-bd00-e10434e22c2c)

Since model is private, I can share it only through private way, so model has been sent to [ifc.js.contact@gmail.com](mailto:ifc.js.contact@gmail.com) with this issue number in subject.

### Version

0.0.54

### What browsers are you seeing the problem on?

Firefox, Chrome

**Comment by Felipemore96** [comment]
Hello! FYI: @agviegas is no longer using the email "ifc.js.contact@gmail.com".

Please send the IFC model to my email fmoreiras@apogeaconsulting.com to check what's the issue or, if necessary, to Antonio's email antonio@thatopen.com so he can share it with me.

**Comment by hellghostx** [comment]
> Hello! FYI: @agviegas is no longer using the email "[ifc.js.contact@gmail.com](mailto:ifc.js.contact@gmail.com)".
> 
> Please send the IFC model to my email [fmoreiras@apogeaconsulting.com](mailto:fmoreiras@apogeaconsulting.com) to check what's the issue or, if necessary, to Antonio's email [antonio@thatopen.com](mailto:antonio@thatopen.com) so he can share it with me.

Hi! Thank you for letting me know! If you don't mind, I know you just from this and another issue, so I will rather choose thatopen.com than apogeaconsulting.com. So model should be at Antonio's thatopen email.

Btw if I am not mistaken, the old email should still have all models with bugfix numbers (at least from my issues), so if the access is not lost it should be all there for Antonio to share :)

**Comment by agviegas** [comment]
Model privately shared [here](https://drive.google.com/file/d/1z9olsSqgjKogT81K9OBQTijYENpN_d4h/view?usp=drive_link)!

**Comment by beachtom** [comment]
This is now fixed!
