### ISSUE TITLE
[Bug]: Unimplemented Geometry in Web-Ifc

### ISSUE THREAD

**Issue by Issa369** [ThatOpen/engine_web-ifc#830]
### What happened?

I will be attaching a link for the problem, keeping in mind that I have tested every possible scenario with every version of web-ifc and every single one of them lead me to web-ifc being the problem for missing implementation of some geometries, this a huge problem that needs a fix asap.
Here is the link of the old issue : [HERE](https://github.com/ThatOpen/engine_web-ifc/issues/786)

### Version

0.0.53

**Comment by Issa369** [comment]
@agviegas

**Comment by agviegas** [comment]
We'll fix it as soon as we can!

**Comment by QuimMoya** [comment]
Solved

![image](https://github.com/ThatOpen/engine_web-ifc/assets/12625508/283b25c9-ee60-44f5-9ef0-129c21a02b73)

**Comment by QuimMoya** [comment]
Solved 

![image](https://github.com/ThatOpen/engine_web-ifc/assets/12625508/365db7b0-d62a-406f-b23e-8be7577f1ae0)

**Comment by Issa369** [comment]
is there a way for me to test it? because there is another model that i want to test.

**Comment by QuimMoya** [comment]
@Issa369 
    
    You can use https://thatopen.github.io/engine_web-ifc/demo
