### ISSUE TITLE
[Bug]: Object missing in the viewer

### ISSUE THREAD

**Issue by vivenHu** [ThatOpen/engine_web-ifc#837]
### What happened?

I'm using the demo viewer provided in the repo page for showcase (needed for our case). And would like to ask if the demo viewer is updated recently.
As shown in the screenshots below. Columns in my IFC file are missing but were there when I tested two weeks ago.
I also Tested with the test build from 27.05.2024 and 13.05.2024 from the "Current build" Tab, the old one shows the column, but the new one doesn't.
![demo_before](https://github.com/ThatOpen/engine_web-ifc/assets/85647844/b8df8666-f674-41ec-9833-99f8883d4eae)
![demo_now](https://github.com/ThatOpen/engine_web-ifc/assets/85647844/33129df7-e51a-4b90-a4ce-285292032aa7)

### Version

0.0.55

### What browsers are you seeing the problem on?

Chrome

**Comment by QuimMoya** [comment]
Can you provide the model?

**Comment by vivenHu** [comment]
> Can you provide the model?

Thank you very much for your fast reply.
I created a test IFC with only columns. [test.zip](https://github.com/ThatOpen/engine_web-ifc/files/15467846/test.zip).
It shows in the old build but not in the demo and new build.
![column before](https://github.com/ThatOpen/engine_web-ifc/assets/85647844/201a4589-c8e5-4fce-8d0c-87a1c3688f1b)

**Comment by QuimMoya** [comment]
I Think it's solved

![image](https://github.com/ThatOpen/engine_web-ifc/assets/12625508/01e478dd-8b86-44ba-98f8-9004c4aeadf8)

**Comment by vivenHu** [comment]
I just tested with the new demo and build. It's fixed.
Thank you very much for the fast fix.
