### ISSUE TITLE
[Bug]: Can't load a 10Mo ifc

### ISSUE THREAD

**Issue by TristanLecallier** [ThatOpen/engine_web-ifc#838]
### What happened?

Hi, 
I've shared with @agviegas an ifc file (10Mo, named not_openable.ifc) which can't be open with engine_web_ifc (https://thatopen.github.io/engine_web-ifc/demo/).  The page freezes (in the console nothing happens after "Opening model took 163 ms")

PS : I had no problem to open it with BimVision.

### Version

0.0.55

**Comment by Felipemore96** [comment]
Hello Tristan! Please share the IFC file to check what's the issue

**Comment by TristanLecallierABIME** [comment]
Hey @agviegas, I'va accepted your request, tell me if you have access.

**Comment by TristanLecallier** [comment]
Hey @agviegas, I'va accepted your request, tell me if you have access.

**Comment by agviegas** [comment]
I do, thanks! [Here](https://drive.google.com/file/d/1OvEaPS2pz8NmDwm-E1hO8rJZib9V2gC2/view?usp=sharing) it is shared privately.

**Comment by QuimMoya** [comment]
The last commit solves this issue
![image](https://github.com/user-attachments/assets/4c592a13-1fbd-4957-ae45-30454adaed92)
