### ISSUE TITLE
[Bug]: Unable to exit Loop and some objects are displayed incorrect

### ISSUE THREAD

**Issue by lzm8607** [ThatOpen/engine_web-ifc#841]
### What happened?

Hello! There is a ifc file can't be loaded, the reason is that when running in function 'InverseMethod', it unable to exit, So I add a variable to limit repeat times and then the model is displayed. But some objects are displayed incorrect.

<img width="1135" alt="20240530-172644@2x" src="https://github.com/ThatOpen/engine_web-ifc/assets/8871950/39bd4ef1-d5c6-470d-a9f7-8d59535eb55c">

![20240530-150458](https://github.com/ThatOpen/engine_web-ifc/assets/8871950/c0a0fa25-527a-4e2e-bc44-dd28548aa47b)
![20240530-150055](https://github.com/ThatOpen/engine_web-ifc/assets/8871950/16cada6d-d914-4afa-974a-63fdcd93e37d)
![20240530-150315](https://github.com/ThatOpen/engine_web-ifc/assets/8871950/6388f5ba-6109-459d-8107-7ba7d43d6dcc)

- ifc file: 
[test.ifc.zip](https://github.com/ThatOpen/engine_web-ifc/files/15496670/test.ifc.zip)

### Version

0.0.53、0.0.54

### What browsers are you seeing the problem on?

Chrome

**Comment by beachtom** [comment]
Yes, that method is not perfect and we haven't got it solved yet. It doesn't always converge.

Are you able to contribute the code you wrote as a PR?

**Comment by QuimMoya** [comment]
It will be solved in the next commit

![image](https://github.com/user-attachments/assets/97642b82-5053-430f-b9b6-34c04d2aa9ce)

Test it tomorrow in the demo [https://thatopen.github.io/engine_web-ifc/demo](https://thatopen.github.io/engine_web-ifc/demo)
