### ISSUE TITLE
[Bug]: IfcBooleanResult not rendering properly (fuzzybools regression?) 

### ISSUE THREAD

**Issue by nickcastel50** [ThatOpen/engine_web-ifc#843]
### What happened?

This looks to be a regression of this: https://github.com/ThatOpen/engine_web-ifc/issues/452

Screenshots from the demo application: 

<img width="663" alt="Screenshot 2024-06-03 at 2 08 32 PM" src="https://github.com/ThatOpen/engine_web-ifc/assets/17447690/be90fcc2-2607-4ffb-b6f9-7d168a51ad7b">
<img width="792" alt="Screenshot 2024-06-03 at 2 08 53 PM" src="https://github.com/ThatOpen/engine_web-ifc/assets/17447690/1c181674-cdad-431a-9637-632667a9c8e0">

It looks to be related to the fuzzy bools update. Let me know if I can provide any more information. 

### Version

latest demo 

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by Felipemore96** [comment]
Hello! Please share the model to check what's the issue

**Comment by nickcastel50** [comment]
Hi @Felipemore96 - it was in the linked issue but it is here as well: https://github.com/Swiss-Property-AG/Momentum-Public/blob/main/Momentum.ifc

**Comment by QuimMoya** [comment]
Yes, this is a regression
We are working on it

**Comment by QuimMoya** [comment]
Now it is solved. Today we will publish
