### ISSUE TITLE
[Bug]: Example not working locally

### ISSUE THREAD

**Issue by untecnologo** [ThatOpen/engine_web-ifc#844]
### What happened?

When I try to see how the example works locally there is an issue with the example and it does not run.
![Screenshot 2024-06-04 011434](https://github.com/ThatOpen/engine_web-ifc/assets/37328540/671da5a6-7516-491d-94ab-bc1b06e4c8e2)
I have tried to fix it but the issue get worst.

Also, I would like to know if you have any integration example with jquery or Js vanilla. 

Thank you for your time and support

### Version

latest

### What browsers are you seeing the problem on?

Chrome

**Comment by beachtom** [comment]
Have you run npm run build-release first? What are you steps to trying the example?

**Comment by beachtom** [comment]
Closing this as nothing heard
