### ISSUE TITLE
[Bug]: Data from flatTransformation returns shifted values since 0.0.51

### ISSUE THREAD

**Issue by hellghostx** [ThatOpen/engine_web-ifc#850]
### What happened?

For a given model with several meshes (cca12) all meshes have wrong data for their geometries. Or rather shifted by a half of their length. Here is example of one of such geometry where first tube is correct and others are shifted by half of their length to the right. 

![obrazek](https://github.com/ThatOpen/engine_web-ifc/assets/26725817/7d5216c7-9bed-4135-9500-dd4cacf2da0b)

I have tracked data from flatTransformation of geometry and there I was able to see this shift as well.

This behaviour started after upgrade from 0.0.47 into 0.0.51 and is still present in 0.0.54.

Also model from issue #420 is rendered like this:

![obrazek](https://github.com/ThatOpen/engine_web-ifc/assets/26725817/f62a383f-25e9-4bdd-830f-9b83232e6ef9)

### Version

0.0.51-0.0.54

### What browsers are you seeing the problem on?

Firefox, Chrome

**Comment by beachtom** [comment]
Is it happening on the demo live on this repo right now? Or can you share the IFC file can I can check?

**Comment by hellghostx** [comment]
> Is it happening on the demo live on this repo right now? Or can you share the IFC file can I can check?

Demo is loading the model correctly. I am not sure if you run master or 0.0.54 on the demo since there is no version in console anymore. If you want model I can share it via email or you can use the model which I have already sent you for #420

**Comment by beachtom** [comment]
ok great - that means it should work with the next release
