### ISSUE TITLE
[Bug]: stol: out of range

### ISSUE THREAD

**Issue by RyugaRyuzaki** [ThatOpen/engine_web-ifc#857]
### What happened?

A bug happened! 
![image](https://github.com/ThatOpen/engine_web-ifc/assets/89787521/7332e934-72f7-4c3d-abd1-73185d9c5b77)

### Version

0.0.53

### Relevant log output

```shell
When i load a model has a large geometry size ( 18km for bounding box)
```

**Comment by beachtom** [comment]
Can you share the model?

**Comment by RyugaRyuzaki** [comment]
> Can you share the model?

Let me tell my CTO then i will share. Thank @beachtom

**Comment by RyugaRyuzaki** [comment]
> Can you share the model?

hi, @beachtom here is file https://drive.google.com/file/d/1bG9XL7M8fB6Ip1PnK2M0jja60dGB2AIK/view?usp=sharing

**Comment by beachtom** [comment]
So in the current version it seems to work fine now not sure if something else fixed it - but it seems to be fine now
