### ISSUE TITLE
[Feat]: Web-ifc + wasm build documentation/tutorial

### ISSUE THREAD

**Issue by Issa369** [ThatOpen/engine_web-ifc#858]
### What is your idea?

i just want to suggest something that might be super helpful to you guys and for your community, how about you guys make a tutorial on how to compile and create our own wasm files and our own web-ifc library build so that people can actually help reduce the bugs that are inside  engin_web-ifc.

Doing so will have a huge impact on you guys's work.

Like for example I'm facing a lot of problem with mis-alignment issues or geometries not render but i cant fix them because the bug is inside web-ifc and i cant upload the library locally and make my own fixes.

**Comment by beachtom** [comment]
Can you let me know what errors you are getting - and I will help. Then we can use this to improve the documentation

**Comment by Issa369** [comment]
I honestly struggled with installing the prerequisites for the web-ifc library to generate for me my custom wasm files, which was something related to "emcmake cmake", I tried downloading the cmake but i failed there was no documentation to follow.
Also i wanted to edit and modify the library to make custom fixes. for example, i want to be able to edit on the whole library ( including creating my wasm files ) and make my own fixes but i have to know how to create the build files.

**Comment by beachtom** [comment]
So generally you need to install cmake from here: https://cmake.org/download/

Then emscripten https://emscripten.org/docs/getting_started/downloads.html and make sure both are in your path.

You also need mingw from here https://sourceforge.net/projects/mingw/

If you've got these installed let me know and we can move onto the next step

**Comment by Issa369** [comment]
Alright I'll let you know what happens

**Comment by beachtom** [comment]
Closing for now - please re-open if you have more questions
