### ISSUE TITLE
[Bug]: Some objects are not parsed

### ISSUE THREAD

**Issue by perstromswe** [ThatOpen/engine_web-ifc#859]
### What happened?

I needed ports (ifcdistrubtionport) and this was a special export option in the model software (magicad export in Revit). After this, I noticed objects where missing. 

No errors. No crash. Just objects missing.

I did a test where I moved an object that were missing from the lower part of the IFC file higher up in the file. Then it worked. Not only were the objects back again, but other objects that were previously missing also reappeared. Really wierd. 

I understand this is tricky to debug without a file. I can give it to you but not in public. Is there email or something to the maintainers where I can send link to a file?

### Version

0.0.54

### Relevant log output

```shell
for (let i = 1; i <= lineSize; i++) {
    try {
      const itemId = lines.get(i);
      if (itemId == null) {
        continue;
      }
      let row: IfcBaseEntity.IRootObject;
      try {
        row = client.GetLine(modelId, itemId);
      } catch (err) {
       console.log(err
        continue;
      }

      if (row.GlobalId.value === '290aexvHH2AP4ov$E8id$g') { 
       console.log(JSON.stringify(row, null, 2)); //This globalId is in the file. It's not logging out.
       }
```

**Comment by beachtom** [comment]
Can you share a model or extract IFC lines from a model?

**Comment by perstromswe** [comment]
Yes. Is there anyway to share the file i private?

**Comment by perstromswe** [comment]
Apparently I need approval from project. I'll get back to you soon.

**Comment by Felipemore96** [comment]
Hello! If you can please also share the model to check what's the issue: fmoreiras@apogeaconsulting.com

**Comment by perstromswe** [comment]
@beachtom file shaered. You should have received an email.

@Felipemore96 thanks but I only have approval to share with Tom.

**Comment by beachtom** [comment]
Nothing recieved as yet? Did you attach it to the mail? Or send a one drive link.

**Comment by beachtom** [comment]
It just arrvied!
