### ISSUE TITLE
[Bug]: Attribute is derived subtype.

### ISSUE THREAD

**Issue by RyugaRyuzaki** [ThatOpen/engine_web-ifc#863]
### What happened?

When i try to create IfcGeometricRepresentationSubContext : 
```
this.IfcGeometricRepresentationSubContext1 =
      new IFC4X3.IfcGeometricRepresentationSubContext(
        new IFC.IfcLabel("Axis"),
        new IFC.IfcLabel("Model"),
        this.IfcAxis2PlacementGlobal3D,
        this.IfcGeometricRepresentationContext,
        new IFC.IfcPositiveRatioMeasure(1e-3),
        IFC.IfcGeometricProjectionEnum.GRAPH_VIEW,
        new IFC.IfcLabel("")
      );
```
Then i checked from here https://validate.buildingsmart.org/dashboard
It threw this error 
![image](https://github.com/ThatOpen/engine_web-ifc/assets/89787521/a0ab2c14-8080-471b-9590-9a35e58b50fd)

### Version

0.0.54

### Relevant log output

```shell
null
```

### Anything else?

null

**Comment by RyugaRyuzaki** [comment]
From snippet :

``` 
constructor IFC4X3.IfcSIUnit(
Dimensions: (Handle<IFC.IfcDimensionalExponents> | IFC.IfcDimensionalExponents),
 UnitType: IFC.IfcUnitEnum, 
Prefix: IFC.IfcSIPrefix | null, 
Name: IFC.IfcSIUnitName): IFC.IfcSIUnit
```
So i follow 
```
 IfcDimensionalExponents: IFC.IfcDimensionalExponents =
    new IFC.IfcDimensionalExponents(1, 1, 1, 1, 1, 1, 1);
  IfcLengthUnit: IFC.IfcSIUnit = new IFC.IfcSIUnit(
    this.IfcDimensionalExponents,
    IFC.IfcUnitEnum.LENGTHUNIT,
    "",
    IFC.IfcSIUnitName.METRE
  );
```
And result 
```
#19= IFCSIUNIT(#18,.LENGTHUNIT.,$,.METRE.);
```
Expected :
```
#19= IFCSIUNIT(*,.LENGTHUNIT.,$,.METRE.);
```
The problem "*" instead "#18".

**Comment by beachtom** [comment]
Can you share the full code for writing it?

**Comment by RyugaRyuzaki** [comment]
> Can you share the full code for writing it?

@beachtom [to define](https://github.com/RyugaRyuzaki/bim-modeling/blob/main/packages/clay/src/base/IfcUnit.ts)
and [to export](https://github.com/RyugaRyuzaki/bim-modeling/blob/main/packages/clay/src/base/IfcInfo.ts#L155) 
and [to writeline](https://github.com/RyugaRyuzaki/bim-modeling/blob/main/packages/clay/src/base/model.ts#L40)

**Comment by beachtom** [comment]
This is fixed!

**Comment by RyugaRyuzaki** [comment]
> This is fixed!

Ops! @beachtom it's still error!
![image](https://github.com/ThatOpen/engine_web-ifc/assets/89787521/2c76d613-c155-4106-9e56-070ab8066473)
Result :
```
#88=IFCSIUNIT(.LENGTHUNIT.,'',.MILLI.,$);
```
Expected :
```
#88=IFCSIUNIT(*,.LENGTHUNIT.,'',.MILLI.,$);
```

**Comment by beachtom** [comment]
Did you test with the code here - new version hasn't been released yet? In any case I will double check

**Comment by RyugaRyuzaki** [comment]
> Did you test with the code here - new version hasn't been released yet? In any case I will double check

yes. i downloaded build.zip then i followed this 
```
    class IfcSIUnit extends IfcNamedUnit {
        UnitType: IfcUnitEnum;
        Prefix: IfcSIPrefix | null;
        Name: IfcSIUnitName;
        type: number;
        constructor(UnitType: IfcUnitEnum, Prefix: IfcSIPrefix | null, Name: IfcSIUnitName);
    }
```
And output 
```
#88=IFCSIUNIT(.LENGTHUNIT.,'',.MILLI.,$);
```

**Comment by JakeOShannessy** [comment]
I think I may be hitting the same or a similar issue with 0.0.61. In the below code I'm writing a minimal IFC file with just a single instance of IfcSIUnit. It outputs the line `#1=IFCSIUNIT(#0,.LENGTHUNIT.,$,.METRE.);` rather than the expects `#1=IFCSIUNIT(*,.LENGTHUNIT.,$,.METRE.);`. My understanding is that the first parameter should be '*' as that is now derived.

Code used to reproduce the issue:
```javascript
import WebIFC from "web-ifc";
import * as fs from "fs";

const ifcApi = new WebIFC.IfcAPI();
await ifcApi.Init();
const newIfcModel = {
    schema: WebIFC.Schemas.IFC4,
    name: `Test Project`,
}
const modelId = ifcApi.CreateModel(newIfcModel);
const metres = new WebIFC.IFC4.IfcSIUnit(
    WebIFC.IFC4.IfcUnitEnum.LENGTHUNIT,
    null,
    WebIFC.IFC4.IfcSIUnitName.METRE
);
ifcApi.WriteLine(
    modelId,
    metres,
);
fs.writeFileSync('test.ifc', ifcApi.SaveModel(modelId));
ifcApi.CloseModel(modelId);
```

Output:
```step
ISO-10303-21;
HEADER;
/******************************************************
* STEP Physical File produced by: That Open Engine WebIfc 0.0.61
* Module: web-ifc/IfcLoader
* Version: 0.0.61
* Source: https://github.com/ThatOpen/engine_web-ifc
* Issues: https://github.com/ThatOpen/engine_web-ifc/issues
******************************************************/
FILE_DESCRIPTION(('ViewDefinition [CoordinationView]'),'2;1');
FILE_NAME('Test Project','2024-11-11T10:58:51',($),($),'thatopen/web-ifc-api','thatopen/web-ifc-api',$);
FILE_SCHEMA(('IFC4'));
ENDSEC;
DATA;
#1=IFCSIUNIT(#0,.LENGTHUNIT.,$,.METRE.);
ENDSEC;
END-ISO-10303-21;
```

**Comment by JakeOShannessy** [comment]
This has resolved the bug for me.
