### ISSUE TITLE
that method has an error in brower run wasm, access memory out of bound

### ISSUE THREAD

**Issue by cnsource** [ThatOpen/engine_web-ifc#866]
https://github.com/ThatOpen/engine_web-ifc/blob/435e9bcebeb430159e989af461fcb16167abb6c2/src/cpp/web-ifc-wasm.cpp#L29

the version 0.0.55

**Comment by beachtom** [comment]
Can you give me sme more information - i.e. an error trace or the model file that causes it

**Comment by beachtom** [comment]
Closing as no response
