### ISSUE TITLE
web-ifc is reloaded for every model

### ISSUE THREAD

**Issue by janruo** [ThatOpen/engine_web-ifc#871]
### Describe the bug 📝

Every time `fragmentIfcLoader.load()` is called, it makes a new request to the 1.1 MB web-ifc wasm file.

The browser will most likely cache the request, and everything seems to be properly garbage collected anyway, so this shouldn't cause any _real_ problems, but it still seems unnecessarily wasteful:

![kuva](https://github.com/ThatOpen/engine_components/assets/49906573/e6dc5c3d-2c97-4eb2-8442-5c3570cf37fb)

### Steps to reproduce 🔢

Call `fragmentIfcLoader.load()` more than once.

### System Info 💻

```shell
@thatopen/components 2.0.6
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by beachtom** [comment]
This is fixed @agviegas somewhere in fragments something is callined ifcAPI.Init() multiple times. But I have added a check so even if it is called multiple times it will not download the wasm again
