### ISSUE TITLE
[Question]: How can I get IFC data such as name or other attributes?

### ISSUE THREAD

**Issue by Philip2809** [ThatOpen/engine_web-ifc#873]
Hello!

I am very new to the IFC file structure and this web-ifc is awesome, I am wondering how I would be able to get IFC metadata from the file to three js based on expressId? For example, in IFC it says:
`#1295= IFCSITE('1b0aQcLSb6KP4cEKR_kZZp',#12,'Gelaende 0815','No real site','LandUse',#104,#1289,$,.ELEMENT.,(49,9,0,0),(8,43,0,0),0.,$,$);`
And I can find `1295` via web-ifc but I cant get the name or other attributes as shown with blenderbim: 
![image](https://github.com/ThatOpen/engine_web-ifc/assets/51290462/966787b5-03ea-43dd-bbfc-e2d9a0b2c799)

How can I get this info? If not possible can this feature be added?

**Comment by beachtom** [comment]
Hi - you should be able to use the GetLine method. This will return an object with all the IFC properties on it. Have you tried that?

**Comment by Philip2809** [comment]
Hey! I am using version 0.0.40 right now, maybe that is too old? This is what I get with GetLine;
![image](https://github.com/ThatOpen/engine_web-ifc/assets/51290462/06951758-ac1e-48d3-b112-392984996ddb)

**Comment by beachtom** [comment]
yes that should work - can you try the latest version?

**Comment by Philip2809** [comment]
The errors are on the small 10mb file

**Comment by beachtom** [comment]
I suspect the version in the console is not keeping the model in memory.

The model you get the errors will only effect the geometric views - you should still be able to get data from it?

**Comment by Philip2809** [comment]
I was wrong, it did load but it took ALOT longer, over a minute, the old version took 10 sec to load the 460 mb file. The 10 mb file loads fast but with the errors as above.

**Comment by Philip2809** [comment]
I can get the data from it, but why does it error?
https://www.steptools.com/docs/stpfiles/ifc/AC20-Institute-Var-2.ifc
This is the example file I use

**Comment by beachtom** [comment]
There are  some meshes in that object we don't support yet.

**Comment by Philip2809** [comment]
I see, thank you for helping me! Can you use web-ifc to modify these attributes?

**Comment by Philip2809** [comment]
It it possible to build a dir-tree with web-ifc in an easy way?

**Comment by beachtom** [comment]
web-ifc is quite low level. I believe the code for building the tree lives in the components repo. So you would need to look at that for inspiration

**Comment by Philip2809** [comment]
Alright, thanks for you help, will look into it!
