### ISSUE TITLE
[Bug]: Model not showing correctly

### ISSUE THREAD

**Issue by armadinho** [ThatOpen/engine_web-ifc#875]
### What happened?

The model that is shown after I load the ifc file seems to have porblems. 
I have tested 3 different files that had no issues when I was using the bim components or the solibri app.
I see that some elements are not rendered correclty.
![image](https://github.com/ThatOpen/engine_web-ifc/assets/6803944/db3d903a-1524-4e9b-ba4e-9c1467b08abe)
![image](https://github.com/ThatOpen/engine_web-ifc/assets/6803944/a50145cd-37dd-412a-928b-e533e3172ed5)

### Version

0.0.54

**Comment by beachtom** [comment]
Can you try the model on the latest demo on the front page of this repo and see if it renders correctly there

**Comment by armadinho** [comment]
Yes it runs fine!

![image](https://github.com/ThatOpen/engine_web-ifc/assets/6803944/e48255d8-e255-41e7-98c9-021b39cb78c0)

**Comment by beachtom** [comment]
great this means it has been fixed here - once components gets updated it will come through there
