### ISSUE TITLE
Some faces are not properly drawn / go missing

### ISSUE THREAD

**Issue by maidi29** [ThatOpen/engine_web-ifc#877]
### Describe the bug 📝

After opening this [issue](https://github.com/ThatOpen/engine_components/issues/423), I realized that the rendering is much better now using the newest versions, but still some faces of the geometry are not properly translated into the scene and are completely missing:

![image](https://github.com/ThatOpen/engine_fragment/assets/8269208/277a64ef-a9d1-463f-bc9d-cd2ace41d613)

As I said, it already went better with the newest versions of the packages so in https://platform.thatopen.com/app even more faces are broken.
I created an example ifc where you can see the issue.

### Reproduction ▶️

https://platform.thatopen.com/app

### Steps to reproduce 🔢

1. use a base ThatOpen Scene
2. upload the following ifc: https://drive.google.com/file/d/1yJKrOzO_eviQBBzldN3FjHoNHRsuUV0r/view
3. see that the one face between wall and window is always missing on the one side

### System Info 💻

```json
"@thatopen/components": "2.0.20",
"@thatopen/fragments": "2.0.5",
"@thatopen/components-front": "2.0.19",
"web-ifc": "0.0.55"
```

**Comment by QuimMoya** [comment]
![image](https://github.com/user-attachments/assets/f4a3f3b3-d7b3-42aa-b2ea-4359507b67f6)
I think it is solved now.

**Comment by maidi29** [comment]
Thank you very much - it is resolved now! 🫶
