### ISSUE TITLE
[Bug]: Can not display Alignments

### ISSUE THREAD

**Issue by BIMengineer1** [ThatOpen/engine_web-ifc#878]
### What happened?

I tried many IFC files with Alignments but the library fails to display them. The civil release has been around for some time (I suppose the library should at least read Alignments correctly), so it's not clear to me why it is not working. Thanks!

### Version

Last version

### Anything else?

![image](https://github.com/ThatOpen/engine_web-ifc/assets/174061299/9ed368a0-cd59-4bf8-866b-b766665defab)

**Comment by beachtom** [comment]
Do you have an example file? It does work in many cases so we need to see what is different? Also the code you are using to pull out the alignments would be good

**Comment by BIMengineer1** [comment]
[IFC.zip](https://github.com/user-attachments/files/16030776/IFC.zip)
@beachtom I tried every template that loads the files, and the model properties are all the same for every load (empty arrays of curves). This one for example https://docs.thatopen.com/Tutorials/Components/Front/Civil3DNavigator , but the result is the same for other templates too.

**Comment by BIMengineer1** [comment]
@beachtom I tried every template that loads the files, and the model properties are all the same for every load (empty arrays of curves). This one for example https://docs.thatopen.com/Tutorials/Components/Front/Civil3DNavigator , but the result is the same for other templates too.
[IFC.zip](https://github.com/user-attachments/files/16030985/IFC.zip)

**Comment by BIMengineer1** [comment]
> @beachtom I tried every template that loads the files, and the model properties are all the same for every load (empty arrays of curves). This one for example https://docs.thatopen.com/Tutorials/Components/Front/Civil3DNavigator , but the result is the same for other templates too. [IFC.zip](https://github.com/user-attachments/files/16030985/IFC.zip)

[testIFC.zip](https://github.com/user-attachments/files/16053597/testIFC.zip)

**Comment by beachtom** [comment]
So that representation of an Alignment is not like I would expect to see. I can't find a clear link between the IFCAlignment in the file and the IFCAlignmentSegments - do you have any other files?

**Comment by BIMengineer1** [comment]
I used the default IFC export for 4x3 and 4x1 from Civil 3D. Basically my files have all the same structure.
What software did you use to export the IFC alignments?

**Comment by BIMengineer1** [comment]
<IfcAlignment id="3px00h4IfFUfqNGQUDcho8" Name="Alignment - (2)" ObjectType="Centerline" ObjectPlacement="1 0 0 0 0 1 0 0 0 0 1 0 -58592 31217 0 1" PredefinedType="USERDEFINED">
				<IfcAlignmentHorizontal id="0L7qsKwKjcP5peSY6rXwkt" Name="Alignment - (2)" ObjectPlacement="1 0 0 0 0 1 0 0 0 0 1 0 -58592 31217 0 1">
					<IfcAlignmentSegment id="2y_ehwC$nXEhkasUnYlZie" ObjectPlacement="1 0 0 0 0 1 0 0 0 0 1 0 -58592 31217 0 1"/>
					<IfcAlignmentSegment id="3xxYD7YMN69C481zzGbIL0" ObjectPlacement="1 0 0 0 0 1 0 0 0 0 1 0 -58592 31217 0 1"/>
					<IfcAlignmentSegment id="0KrJ9d$nJ2O28z2njQIkwn" ObjectPlacement="1 0 0 0 0 1 0 0 0 0 1 0 -58592 31217 0 1"/>
					<IfcPropertySet xlink:href="#3ZtGKy5MvAwOS7V5RSn2_M"/>
					<IfcPropertySet xlink:href="#0b3ovwxtnDsxsdgpKI1tWu"/>
					<IfcPropertySet xlink:href="#229dCSjSXB09wxea84DnHN"/>
					<IfcPropertySet xlink:href="#0FlAVVZUf8Seu2cRRNQOe7"/>
					<IfcPropertySet xlink:href="#1vExY8GJH0eBb9nufQD_Sx"/>
					<IfcPropertySet xlink:href="#2cbXbLYgvB3f3WrZD3Rtzz"/>
				</IfcAlignmentHorizontal>
				<IfcAlignmentVertical id="1xXLPLnlwFGFcZP3cNNLix" Name="Profile - (1)" ObjectType="FG" ObjectPlacement="1 0 0 0 0 1 0 0 0 0 1 0 -58592 31217 0 1">
					<IfcAlignmentSegment id="2D_juxjzcyzks3c9L5Ik0K" ObjectPlacement="1 0 0 0 0 1 0 0 0 0 1 0 -58592 31217 0 1"/>
					<IfcPropertySet xlink:href="#3XxQp2INr8FxYIcofgxNTv"/>
					<IfcPropertySet xlink:href="#3ltkx6qAf9rh9U1vHntcBx"/>
					<IfcPropertySet xlink:href="#2oOWOfZOXEeAd7OdiTxFXe"/>
					<IfcPropertySet xlink:href="#12XrzwEs16Qfq9dy1MZWA7"/>
					<IfcPropertySet xlink:href="#0gLLzS3bL8OvCqq1rp1Qel"/>
					<IfcPropertySet xlink:href="#0xacKKt$90DfrFtEHT9kby"/>
				</IfcAlignmentVertical>
				<IfcReferent id="0fF3_YnOI2xf9bGsXw3EbA" Name="BP: 0+000.00" PredefinedType="REFERENCEMARKER"/>
				<IfcReferent id="15Pd_uHZ5_B3RVvROn8IoX" Name="PC: 0+095.85" PredefinedType="REFERENCEMARKER"/>
				<IfcReferent id="0rNz507ampk_3AOP6MK7Is" Name="Mid: 0+141.77" PredefinedType="REFERENCEMARKER"/>
				<IfcReferent id="2oA28F019KHduieXzXuDOM" Name="EP: 0+187.70" PredefinedType="REFERENCEMARKER"/>
				<IfcReferent id="0XnBRL0UsLxEywhF9VHAeN" Name="0+000" PredefinedType="REFERENCEMARKER"/>
				<IfcReferent id="31GvwC8gS8h2b9Z0AXz4QV" Name="0+020" PredefinedType="REFERENCEMARKER"/>
				<IfcReferent id="0r$xpW5vfYBZFPHsV5LcGL" Name="0+040" PredefinedType="REFERENCEMARKER"/>
				<IfcReferent id="3JziSb1LyWtzTA5vAs_h1t" Name="0+060" PredefinedType="REFERENCEMARKER"/>
				<IfcReferent id="1nmoUgZpi6gM9xApQIOPOq" Name="0+080" PredefinedType="REFERENCEMARKER"/>
				<IfcReferent id="0g7OEg7E04DCkZNmiPgMKc" Name="0+100" PredefinedType="REFERENCEMARKER"/>
				<IfcReferent id="3ygyN3JPCgDPuD6u_pPGWG" Name="0+120" PredefinedType="REFERENCEMARKER"/>
				<IfcReferent id="0$0MSGzsiuwXOW1Tt3iBGN" Name="0+140" PredefinedType="REFERENCEMARKER"/>
				<IfcReferent id="1hR1gGyAo2SBkkPGL5wYZd" Name="0+160" PredefinedType="REFERENCEMARKER"/>
				<IfcReferent id="0ygHxcchHfFJ$Cy2PyTnsc" Name="0+180" PredefinedType="REFERENCEMARKER"/>
				<IfcReferent id="0aYtrWHhtanGE7RbOWR5YP" Name="0+188" PredefinedType="REFERENCEMARKER"/>
				<IfcPropertySet xlink:href="#0l0OcimVfBR9vDt7dYTLTK"/>
				<IfcPropertySet xlink:href="#1hWbgTWuTAnefd7tNyy4Oc"/>
				<IfcPropertySet xlink:href="#1sl9IkgjDBBO9AJX9PU55h"/>
				<IfcPropertySet xlink:href="#2iyXQkMgHAAQHU8eJyd3b7"/>
				<IfcPropertySet xlink:href="#1JN1itBmfCzPQtDyJz6SXi"/>
				<IfcPropertySet xlink:href="#339Cirxk1BOAL4HnqHU9Nr"/>
			</IfcAlignment>
This is the xml structure of the last file.

**Comment by BIMengineer1** [comment]
<IfcAlignment id="3px00h4IfFUfqNGQUDcho8" Name="Alignment - (2)" ObjectType="Centerline" ObjectPlacement="1 0 0 0 0 1 0 0 0 0 1 0 -58592 31217 0 1" PredefinedType="USERDEFINED">
				<IfcAlignmentHorizontal id="0L7qsKwKjcP5peSY6rXwkt" Name="Alignment - (2)" ObjectPlacement="1 0 0 0 0 1 0 0 0 0 1 0 -58592 31217 0 1">
					<IfcAlignmentSegment id="2y_ehwC$nXEhkasUnYlZie" ObjectPlacement="1 0 0 0 0 1 0 0 0 0 1 0 -58592 31217 0 1"/>
					<IfcAlignmentSegment id="3xxYD7YMN69C481zzGbIL0" ObjectPlacement="1 0 0 0 0 1 0 0 0 0 1 0 -58592 31217 0 1"/>
					<IfcAlignmentSegment id="0KrJ9d$nJ2O28z2njQIkwn" ObjectPlacement="1 0 0 0 0 1 0 0 0 0 1 0 -58592 31217 0 1"/>
					<IfcPropertySet xlink:href="#3ZtGKy5MvAwOS7V5RSn2_M"/>
					<IfcPropertySet xlink:href="#0b3ovwxtnDsxsdgpKI1tWu"/>
					<IfcPropertySet xlink:href="#229dCSjSXB09wxea84DnHN"/>
					<IfcPropertySet xlink:href="#0FlAVVZUf8Seu2cRRNQOe7"/>
					<IfcPropertySet xlink:href="#1vExY8GJH0eBb9nufQD_Sx"/>
					<IfcPropertySet xlink:href="#2cbXbLYgvB3f3WrZD3Rtzz"/>
				</IfcAlignmentHorizontal>
				<IfcAlignmentVertical id="1xXLPLnlwFGFcZP3cNNLix" Name="Profile - (1)" ObjectType="FG" ObjectPlacement="1 0 0 0 0 1 0 0 0 0 1 0 -58592 31217 0 1">
					<IfcAlignmentSegment id="2D_juxjzcyzks3c9L5Ik0K" ObjectPlacement="1 0 0 0 0 1 0 0 0 0 1 0 -58592 31217 0 1"/>
					<IfcPropertySet xlink:href="#3XxQp2INr8FxYIcofgxNTv"/>
					<IfcPropertySet xlink:href="#3ltkx6qAf9rh9U1vHntcBx"/>
					<IfcPropertySet xlink:href="#2oOWOfZOXEeAd7OdiTxFXe"/>
					<IfcPropertySet xlink:href="#12XrzwEs16Qfq9dy1MZWA7"/>
					<IfcPropertySet xlink:href="#0gLLzS3bL8OvCqq1rp1Qel"/>
					<IfcPropertySet xlink:href="#0xacKKt$90DfrFtEHT9kby"/>
				</IfcAlignmentVertical>
				<IfcReferent id="0fF3_YnOI2xf9bGsXw3EbA" Name="BP: 0+000.00" PredefinedType="REFERENCEMARKER"/>
				<IfcReferent id="15Pd_uHZ5_B3RVvROn8IoX" Name="PC: 0+095.85" PredefinedType="REFERENCEMARKER"/>
				<IfcReferent id="0rNz507ampk_3AOP6MK7Is" Name="Mid: 0+141.77" PredefinedType="REFERENCEMARKER"/>
				<IfcReferent id="2oA28F019KHduieXzXuDOM" Name="EP: 0+187.70" PredefinedType="REFERENCEMARKER"/>
				<IfcReferent id="0XnBRL0UsLxEywhF9VHAeN" Name="0+000" PredefinedType="REFERENCEMARKER"/>
				<IfcReferent id="31GvwC8gS8h2b9Z0AXz4QV" Name="0+020" PredefinedType="REFERENCEMARKER"/>
				<IfcReferent id="0r$xpW5vfYBZFPHsV5LcGL" Name="0+040" PredefinedType="REFERENCEMARKER"/>
				<IfcReferent id="3JziSb1LyWtzTA5vAs_h1t" Name="0+060" PredefinedType="REFERENCEMARKER"/>
				<IfcReferent id="1nmoUgZpi6gM9xApQIOPOq" Name="0+080" PredefinedType="REFERENCEMARKER"/>
				<IfcReferent id="0g7OEg7E04DCkZNmiPgMKc" Name="0+100" PredefinedType="REFERENCEMARKER"/>
				<IfcReferent id="3ygyN3JPCgDPuD6u_pPGWG" Name="0+120" PredefinedType="REFERENCEMARKER"/>
				<IfcReferent id="0$0MSGzsiuwXOW1Tt3iBGN" Name="0+140" PredefinedType="REFERENCEMARKER"/>
				<IfcReferent id="1hR1gGyAo2SBkkPGL5wYZd" Name="0+160" PredefinedType="REFERENCEMARKER"/>
				<IfcReferent id="0ygHxcchHfFJ$Cy2PyTnsc" Name="0+180" PredefinedType="REFERENCEMARKER"/>
				<IfcReferent id="0aYtrWHhtanGE7RbOWR5YP" Name="0+188" PredefinedType="REFERENCEMARKER"/>
				<IfcPropertySet xlink:href="#0l0OcimVfBR9vDt7dYTLTK"/>
				<IfcPropertySet xlink:href="#1hWbgTWuTAnefd7tNyy4Oc"/>
				<IfcPropertySet xlink:href="#1sl9IkgjDBBO9AJX9PU55h"/>
				<IfcPropertySet xlink:href="#2iyXQkMgHAAQHU8eJyd3b7"/>
				<IfcPropertySet xlink:href="#1JN1itBmfCzPQtDyJz6SXi"/>
				<IfcPropertySet xlink:href="#339Cirxk1BOAL4HnqHU9Nr"/>
			</IfcAlignment>

**Comment by BIMengineer1** [comment]
[myIFC4X3_ADD1.zip](https://github.com/user-attachments/files/16150873/myIFC4X3_ADD1.zip)
This one from Trimble also. 
I don't understand what structure does the library expect to read the alignments. Does it work with your custom made IFC from the tutorials only?

**Comment by beachtom** [comment]
So often in the IFC there are multiple ways to represent the same thing. It seems we have only dealt with one of the ways. I need to investigate the model some more and look at how it is different

**Comment by QuimMoya** [comment]
Hello
The provided files use different IFC formats, the first one use 4X1 while the other use 4X3_ADD2

To provide support for alignments in 4X1 we have to read a completely different structure, which we did at some point but deprecated with new versions. We can just add it again but it requires sometime as we have to read different elements and a different structure

Anyway we prioritize providing support for latest versions like 4X3_ADD2. This version uses IFCRELNESTS in spite of IFCRELAGGREGATES to connect IFCALIGNMENT with IFCALIGNMENTHORIZONTAL. We were using IFCRELAGGREGATES but we adapted it to read IFCRELNESTS too, so now it should read the alignments of the second model.

**Comment by QuimMoya** [comment]
Probably you have to wait until next release. Anyway you can test it using the demo viewer https://thatopen.github.io/engine_web-ifc/demo/

By pressing f12 you will see info about alignments

![image](https://github.com/user-attachments/assets/a972fbbb-2689-4e56-9800-670b564f2107)
