### ISSUE TITLE
[Bug]: ERROR:  Unsupported Schema:IFC4X3_ADD1

### ISSUE THREAD

**Issue by agviegas** [ThatOpen/engine_web-ifc#884]
### What happened?

A file where the schema is `IFC4X3_ADD1` is not read. If I manually change it to `IFC4X3`, it works perfectly. A file where this happens can be found [here](https://drive.google.com/file/d/1qOTMYpV2Agjnxj7CkamVNuWZMs_c-ngW/view?usp=drive_link). This can be reproduced by opening it in the [demo](https://thatopen.github.io/engine_web-ifc/demo/).

### Version

0.0.55

### Relevant log output

```shell
web-ifc-viewer.js:246859 ERROR:  Unsupported Schema:IFC4X3_ADD1
error	@	web-ifc-viewer.js:246859
```

**Comment by beachtom** [comment]
Fixed
