### ISSUE TITLE
[Bug]: IfcGloballyUniqueId not giving compliant GUID.

### ISSUE THREAD

**Issue by HoyosJuan** [ThatOpen/engine_web-ifc#893]
### What happened?

As the title says, when creating a new GUID the results seem to not get well compressed based on the IFC schema.

### Version

0.0.55

### What browsers are you seeing the problem on?

Chrome

### Anything else?

![image](https://github.com/ThatOpen/engine_web-ifc/assets/84806689/a78d7eb5-0e78-42dc-95b0-d80d784260ac)

**Comment by beachtom** [comment]
So there is no code in web-ifc to compress guids. We assume they are already compressed before being password to the library via write line. So something else is causing this.
