### ISSUE TITLE
[Bug]: IfcMappedItem used in multiple items with one in wrong location

### ISSUE THREAD

**Issue by sennhvi** [ThatOpen/engine_web-ifc#895]
### What happened?

When attempting to parse ifc file containing IFCMappedItem entities through web-ifc, one column appears misplaced. This issue persists when tested using the [demo ](https://thatopen.github.io/engine_web-ifc/demo/) page, the ifc file can be downloaded from [here](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/FINAL/HTML/annex/annex-e/ifc/mapped_shape_multiple.ifc.htm)

![image](https://github.com/ThatOpen/engine_web-ifc/assets/31751605/38e046a2-ba9e-4ec9-a481-de8bbd769f2c)

![image](https://github.com/ThatOpen/engine_web-ifc/assets/31751605/8890f564-3063-43a3-864c-a379e76f7629)

### Version

0.0.54

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by Felipemore96** [comment]
Hello! That link doesn't provide an actual downloadable IFC file, if you can please share the model to check what's the issue. fmoreiras@apogeaconsulting.com

**Comment by sennhvi** [comment]
@Felipemore96 Glad to tell you that this issue was fixed after upgrading the version of web-ifc library to  0.0.56 :)
