### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by perstromswe** [ThatOpen/engine_web-ifc#914]
### What happened?

Trying to run web-ifc in a react app.

When i run ifcApi.init i get Webassebly-related errors in console.

```
import * as WebIfc from 'web-ifc';

const App = () => {

  const ifcApi = new WebIfc.IfcAPI();
  ifcApi.Init();


  return (
    <div className="App">
      Test
    </div>
  )
}

export default App

```
### Version

0.0.54

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

<img width="1285" alt="image" src="https://github.com/ThatOpen/engine_web-ifc/assets/2387327/ffe2d0f3-6379-4268-9619-12a2dc0b43bb">

### Anything else?

Used this template to create the app https://github.com/reduxjs/redux-templates/tree/master/packages/vite-template-redux

**Comment by beachtom** [comment]
So the wasm files should be in your public directory or equivalent. You also need to check that the server is set up to return the wasm mime type for wasm-files.

**Comment by perstromswe** [comment]
Thanks works. Not that obvious. Maybe ad this to quick setup in readme?
