### ISSUE TITLE
Civil - can't read alignment  

### ISSUE THREAD

**Issue by SBrida** [ThatOpen/engine_web-ifc#926]
### Describe the bug 📝

i tried 3 files with alignement but the property Civil inside fragmenetgroup is empty. and an error unexpected mesh 

![Screenshot 2024-05-08 124318](https://github.com/ThatOpen/engine_components/assets/147074562/d9aa1872-4844-42b3-a53a-c8403f5b8618)
![Screenshot 2024-05-08 165313](https://github.com/ThatOpen/engine_components/assets/147074562/5535a37d-8a30-4d20-8b35-8889b4c93368)

### System Info 💻

```shell
openBim-componant 1.5
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ervinalla99** [comment]
@agviegas I think this is solved currently as I see the last commit , and every the IFC 4x3 I tried is parsed correctly here [thatopen.github.io/engine_web-ifc/demo](https://thatopen.github.io/engine_web-ifc/demo). However, when I load it in the engine template it is still empty (I replaced the web ifc folder with the current live version from github)
![image](https://github.com/user-attachments/assets/79d10845-a363-436d-96dc-1a55d9e04802)
What can be the reason?

**Comment by ervinalla99** [comment]
@agviegas I tried the last version of components and it works fine. Thanks a lot!
