### ISSUE TITLE
IfcBooleanClippingResult not rendered correctly

### ISSUE THREAD

**Issue by muren400** [ThatOpen/engine_web-ifc#933]
### What happened?

Hi,

I got [this](https://github.com/user-attachments/files/16237602/Subtraction.ifc.txt) IFC file which contains a wall and two overlapping openings. The openings themselves consist of two extrusions each. When rendering the wall, the opening is not rendered correctly. Maybe fuzzybooleans cant handle those "double chambered" openings?

Those flaps in front of the opening shouldn't be there.
![image](https://github.com/user-attachments/assets/2ce89b83-3221-43a2-a434-75b7749b6ff7)

These are the IfcOpeningElements:
![image](https://github.com/user-attachments/assets/bdfed881-09ac-4f0a-aa27-59d74c8eb801)
![image](https://github.com/user-attachments/assets/5f08907c-04d1-4747-ab89-6f284eca2913)

Maybe it was just one edge case too many.

Thanks,
Andreas

### Version

0.0.56

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by QuimMoya** [comment]
![image](https://github.com/user-attachments/assets/d424128a-b7f2-4cb7-8f35-0d2288887310)
Solved!

It was an issue with the plane addition in the boolean operator
