### ISSUE TITLE
[Bug]: IFC files involving IFCCLOSEDSHELL entities appear to look weird, and some of the faces appear to be stretched

### ISSUE THREAD

**Issue by sennhvi** [ThatOpen/engine_web-ifc#938]
### What happened?

I have an ifc file that shows the soil layers, and the main entity paths involved in the soil layers' content is: IFCBUILDINGELEMENTPROXY->IFCPRODUCTDEFINITIONSHAPE->IFCMAPPEDITEM->IFCFACETEDBREP->IFCCLOSEDSHELL->IFCFACE->IFCFACEOUTERBOUND->IFCPOLYLOOP->IFCCARTESIANPOINT.

In the bimbase browser/BIMVision software, the effect is more reasonable, 
![image](https://github.com/user-attachments/assets/2e2d61ae-69c6-40c0-955c-69f89f2cf639)

![image](https://github.com/user-attachments/assets/7f45a8fc-dd6a-449a-8bc6-80a897a12a42)

in the web-ifc demo page [https://[thatopen.github.io/engine_web-ifc/demo/](https://thatopen.github.io/engine_web-ifc/demo/)] some triangles are stretched far away, why is this?
![image](https://github.com/user-attachments/assets/ef08dba2-eac8-49cd-8e5b-60701e8a12ab)

while parsing ifc file, an error log occurs: [WEB-IFC][error][GetLocalPlacement()] unexpected placement type 236. Entity 236 is #236= IFCCARTESIANPOINT((806766.25,37.849998474121094,376751.46875)); 

### Version

0.0.55

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by sennhvi** [comment]
Here is sample ifc file.Any analysis or solution is greatly appreciated!
[weird-placement.txt](https://github.com/user-attachments/files/16246512/weird-placement.txt)

**Comment by QuimMoya** [comment]
We found the cause of this bug. Some point coordinates are not defined as doubles but integers (does not have a dot at the end of the number value) therefore the parser does not read them properly.
By solving this issue we can open the model 
![image](https://github.com/user-attachments/assets/9b770a54-71bf-4951-8169-f7c1100a7e2b)


But this is not so simple. According to the IFC specs numbers for coordinates should be doubles, not integers. So we still have to decide what to do
