### ISSUE TITLE
[Bug]: Link of Demo and link of actual build is different

### ISSUE THREAD

**Issue by rkaeplive** [ThatOpen/engine_web-ifc#955]
### What happened?

Hello, can you update actual build please 
https://thatopen.github.io/engine_web-ifc/build.zip  -  I think is not actual 
I need this version please!
(https://thatopen.github.io/engine_web-ifc/demo/)

### Version

0.0.56

**Comment by beachtom** [comment]
It seems to be working now.

There may have been issues with github runners earlier in the week - but it looks the same version now
