### ISSUE TITLE
[Bug]: Profiler Geometry not showing

### ISSUE THREAD

**Issue by jimbosquash** [ThatOpen/engine_web-ifc#966]
### What happened?

geometry not showing in small model. see images bellow. 2 geometries in the model and only one showing up. they are constructed using profiles, extrusions and Boolean operations. [https://drive.google.com/drive/folders/1a8KY8WwjQSbLmHavSVaRkFUDH4K2OCK0?usp=sharing](url)

### Version

0.0.55

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
no log given
```

### Anything else?

my personal app using your system at [www.augmentedworkshop.com](url)

![image](https://github.com/user-attachments/assets/cc93d706-1130-42b9-8882-55fec2acfd0d)

navis works. 
![image](https://github.com/user-attachments/assets/4d082510-439b-445f-94d5-caf4583c614a)

Bimvision

![image](https://github.com/user-attachments/assets/a96d9cd4-122a-44d7-a017-b49d184f6a50)

**Comment by jimbosquash** [comment]
here is the google drive link with multiple test files incase link in bug report is broken.

[https://drive.google.com/drive/folders/1a8KY8WwjQSbLmHavSVaRkFUDH4K2OCK0?usp=sharing](url)

**Comment by agviegas** [comment]
More files privately available [here](https://drive.google.com/drive/folders/1-iftLeE_A6hTWG_ykHf5q9nxvRfjBUgl?usp=drive_link).

**Comment by QuimMoya** [comment]
![image](https://github.com/user-attachments/assets/be951e7a-32a5-4310-81e1-53427e8996ed)

IThere was a limit on the recursive call of GetMesh function that prevents it to open these models properly.

At the moment i will remove this limit, but there is a problem with recursive calls.

Anyway it solves your issue.

**Comment by jimbosquash** [comment]
Thank you @QuimMoya , your amazing I appreciate you taking a look and the reason is a curious insight for me too. Thanks!
