### ISSUE TITLE
[Bug]: Geometry error with many version from @0.0.46 to @0.0.56

### ISSUE THREAD

**Issue by RyugaRyuzaki** [ThatOpen/engine_web-ifc#973]
### What happened?

A bug happened! This is geometry error with many version from @0.0.46 to @0.0.56.
I tested and compare  Bim-Vission. Here is [bim-vission](https://drive.google.com/file/d/1Ce1VvA1d3AdUOmP6jMd4rh7dc_6MriCr/view?usp=sharing) [@0.0.46](https://drive.google.com/file/d/1_AWQ94wp8cRBE-fiRyIvum0jgt4uKWJU/view?usp=sharing) [@0.0.55](https://drive.google.com/file/d/1gB3LFbqwof79n6j6vVmqoXQas0Nrrhtw/view?usp=sharing) [@0.0.56](https://drive.google.com/file/d/1l-olhIJ6AZV3_R7mMpFiCIm52CnXJU4G/view?usp=sharing)

### Version

@0.0.46 to @0.0.56

**Comment by QuimMoya** [comment]
Can you share the model with us?

**Comment by RyugaRyuzaki** [comment]
> Can you share the model with us?

Well, it's private,. Let me ask my CTO then will send you.

**Comment by QuimMoya** [comment]
@RyugaRyuzaki Not necessarily the entire model, only those parts that fail.

**Comment by RyugaRyuzaki** [comment]
@QuimMoya hi, here is [the model](https://drive.google.com/file/d/1-gIgRI6Jyrdl0ZlAA9TfJ0MHIDOsXs5p/view?usp=sharing)

**Comment by QuimMoya** [comment]
Is it solved?

![image](https://github.com/user-attachments/assets/e514c15b-f996-4c81-868b-d018ae1fe812)

**Comment by RyugaRyuzaki** [comment]
> Is it solved?
> 
> ![image](https://private-user-images.githubusercontent.com/12625508/370157070-e514c15b-f996-4c81-868b-d018ae1fe812.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNjQwMTMsIm5iZiI6MTcyNzE2MzcxMywicGF0aCI6Ii8xMjYyNTUwOC8zNzAxNTcwNzAtZTUxNGMxNWItZjk5Ni00YzgxLTg2OGItZDAxOGFlMWZlODEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDA3NDE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczMGMyMmFjOWNlNmU5NjBhYTIxOWIwZjQ5NjUzZjkxYzY2ZTFmYzE4MDI4ZDY5MzI4YjMwNmI5YzllNzAzNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CE1E2tn-c7Ww9dR14FXOhHol3-iTSE0J2QcePKizW60)

hi let me test. Is this for new version?web-ifc@0.0.58

**Comment by RyugaRyuzaki** [comment]
> Is it solved?
> 
> ![image](https://private-user-images.githubusercontent.com/12625508/370157070-e514c15b-f996-4c81-868b-d018ae1fe812.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNjUxNDQsIm5iZiI6MTcyNzE2NDg0NCwicGF0aCI6Ii8xMjYyNTUwOC8zNzAxNTcwNzAtZTUxNGMxNWItZjk5Ni00YzgxLTg2OGItZDAxOGFlMWZlODEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDA4MDA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyMGE5YTk2N2MxYTkzZjFiMWQ5YWVhODUxZDMwYWJkOTQxMWNhY2YxOTQyMzA1NmI5OWExYmRiYjhhZDhkMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ufg33PoeZWWyQHbCyo5sIrdU0f8lc-Msnl-j4YVJBuU)

Hi it worked with new version. i will close this. Many thank!
