### ISSUE TITLE
geometrical problems on rendering an IFC file

### ISSUE THREAD

**Issue by ngorlani** [ThatOpen/engine_web-ifc#98]
Hi! I have geometrical problems on rendering an IFC file ([R8_F1_MAB_AR_M3_XX_XXX_MO_7000.zip](https://github.com/tomvandig/web-ifc/files/7427026/R8_F1_MAB_AR_M3_XX_XXX_MO_7000.zip)).
All window geometries are malformed:
![134960418-4eb093d6-6cb9-42c9-b134-23b3ca4650c1](https://user-images.githubusercontent.com/91492685/139087853-8c72a59d-53fe-4657-8bff-93014042efe3.jpg)

**Comment by tomvandig** [comment]
![image](https://user-images.githubusercontent.com/49716596/139532080-9a4e6150-a28d-44d9-8bfc-11b69bb74825.png)
Some more progress at https://tomvandig.github.io/web-ifc/examples/viewer/index.html

**Comment by ngorlani** [comment]
Hi,
perfect!
I'm trying the viewer ( https://tomvandig.github.io/web-ifc/examples/viewer/index.html) and most of the problems now are solved!
I only see this geometrical isseus on windows:
![image](https://user-images.githubusercontent.com/91492685/139909606-64564914-f91b-4eaa-a881-ca388ee9bc7e.png)

**Comment by beachtom** [comment]
I've tried the model myself and from what I can see this should now be fixed
