### ISSUE TITLE
[Bug]: Colors not displaying correctly

### ISSUE THREAD

**Issue by agviegas** [ThatOpen/engine_web-ifc#983]
### What happened?

The colors for [this model](https://drive.google.com/file/d/1hf_zek8WdKVMbyrPgwS5EJzoyZce0kDb/view?usp=drive_link) are not displaying correctly. 

![image](https://github.com/user-attachments/assets/948c56dc-582a-494b-aa26-5313f52fc7a0)

### Version

0.0.56

**Comment by beachtom** [comment]
I was looking at this - but I can't find any actual stylings in the model at all - which is why everything is the default color. I suspect this is a model export issue
