### ISSUE TITLE
[Feat]: Output file size when build bundler.

### ISSUE THREAD

**Issue by RyugaRyuzaki** [ThatOpen/engine_web-ifc#985]
### What is your idea?

I should try to reduce the bundler output file size when building. I used splitVendorChunkPlugin in vite.
```
/* eslint-disable import/no-extraneous-dependencies */
import {defineConfig, splitVendorChunkPlugin} from "vite";

export default defineConfig({
  plugins: [splitVendorChunkPlugin()],
  base: "./",
  esbuild: {
    supported: {
      "top-level-await": true,
    },
  },
  build: {
    chunkSizeWarningLimit: false,
    rollupOptions: {
      output: {
        manualChunks(id: string) {
          // creating a chunk to @open-ish deps. Reducing the vendor chunk size
          if (id.includes("three")) {
            return "three.min";
          }
          if (id.includes("web-ifc")) {
            return "web-ifc.min";
          }
        },
      },
    },
  },
});
```
![image](https://github.com/user-attachments/assets/b4bebba5-fbf7-41cd-9b5c-de5b8ba30a60)
As you can see, the largest file result is in the web-ifc library. After researching, it comes from[ this file.](https://github.com/ThatOpen/engine_web-ifc/blob/main/src/ts/ifc-schema.ts)

The question is whether in the [@web-ifc](https://github.com/ThatOpen/engine_web-ifc/tree/main) library it is possible to separate that file.

Normally I import it through 🤦 
```
import * as WEBIFC from 'web-ifc';
```

Now I'll load a simple file, I'll check its schema, let's say it's IFC2X3, so just...
````
import {IFC2X3} from 'web-ifc';
````
So is it possible to split [this file](https://github.com/ThatOpen/engine_web-ifc/blob/main/src/ts/ifc-schema.ts) into files corresponding to its schema such as IFC2X3,...?

**Comment by beachtom** [comment]
So - the issues if it was a split file - what app you build would only be able to then work with one version of IFC. web-ifc itself needs the version associated with the IFC file it is reading in order to parse it.

**Comment by RyugaRyuzaki** [comment]
> So - the issues if it was a split file - what app you build would only be able to then work with one version of IFC. web-ifc itself needs the version associated with the IFC file it is reading in order to parse it. 

You were right. I think we need that file to detect file's schema.
