### ISSUE TITLE
[Bug]: Wrong triangle visualisation

### ISSUE THREAD

**Issue by hellghostx** [ThatOpen/engine_web-ifc#993]
### What happened?

Web-ifc demo: 

![obrazek](https://github.com/user-attachments/assets/a35b59f0-478c-48c4-8b02-c1f2076f88e9)

What is expected:

![obrazek](https://github.com/user-attachments/assets/5ec43b6a-45d5-4fce-871a-d9a79b8b2838)

### Version

0.0.57

### What browsers are you seeing the problem on?

Chrome

**Comment by hellghostx** [comment]
Model can be shared only for development purposes, so it has been sent to [antonio@thatopen.com](mailto:antonio@thatopen.com).

**Comment by agviegas** [comment]
Model privately available [here](https://drive.google.com/file/d/1O3neXR6ramVw0po8Yv4MqogH7NFprvJO/view?usp=drive_link).

**Comment by sennhvi** [comment]
Try version 0.0.54 see if bug exists

**Comment by hellghostx** [comment]
> Try version 0.0.54 see if bug exists

![obrazek](https://github.com/user-attachments/assets/1f3dd286-7358-43e8-a2fb-190b105a16c0)

It is better but not correct.

**Comment by QuimMoya** [comment]
partially solved on one side
![image](https://github.com/user-attachments/assets/f397abe7-de99-41a7-8f28-333f08a71211)

**Comment by QuimMoya** [comment]
But strangely it still fails on the other side.

**Comment by QuimMoya** [comment]
![image](https://github.com/user-attachments/assets/da7a0d67-dc59-4000-8264-867b46307b73)
I think i solved both sides now, i think i solved this issue
