### ISSUE TITLE
[Bug]: /examples/nodejs exported.ifc does not load in BIMvision 2.28.0

### ISSUE THREAD

**Issue by bymartin** [ThatOpen/engine_web-ifc#994]
### What happened?

Ran the index.js example in /examples/nodejs. I am able to load the example.ifc in BIMvision 2.28.0. I get an error when trying to load the new IFC called exported.ifc. Screenshot below.

![image](https://github.com/user-attachments/assets/53afd2b4-817f-4ca3-9b69-8e42e6149d89)

### Version

0.0.57

### Relevant log output

```shell
The exported.ifc is invalid.
Cannot open IFC model.
Cannot read the parameter list - 13862=IFCPROPERTYSINGLEVALUE(
```

**Comment by bymartin** [comment]
Looking at the last lines of the exported.ifc: 
#14313=IFCPROPERTYSINGLEVALUE(14313.,'Classification',$,'New value');
#14314=IFCPROPERTYSINGLEVALUE(14314.,'Special Number',$,0.16);
#14315=IFCPROPERTYSINGLEVALUE(14315.,'Special Number',$,1E+08);
#14316=IFCPROPERTYSINGLEVALUE(14316.,'Unicode',$,'Ph\X2\00E4\X0\sen');
#14317=IFCPROPERTYSET(14317.,'350fFD9fjAtPfVihcqa4Yn',#41,'Classification','Description');

The propertySet #14317 is not present in any IFCRELDEFINESBYPROPERTIES (not linked up). And doesn't seem like #14314-#14316 are connect to the property set #14317.

**Comment by beachtom** [comment]
Hi, to be honest this file is just for testing - it is not supposed to be viewable really.
