### ISSUE TITLE
[Bug]: Exponential growth of vertices for higher circle_segments

### ISSUE THREAD

**Issue by hellghostx** [ThatOpen/engine_web-ifc#995]
### What happened?

Since version 0.0.55 there has been a change how many vertices are returned from getVertexArray().

For attached model 1st mesh, 1st geometry returns this number of vertices:
 **version < 0.0.55:**
 18288 vertices for 128 segments / 16848 for 10 segments
 **version >= 0.0.55:**
 1773936 vertices for 128 segments / 275184 for 40 segments / 16848 for 10 segments.
 
This means that loading times goes up to minutes or tens of minutes instead of seconds as it was before. Quality of rendered circles is not better for lower number of circle_segments since 0.0.55, so lowering number of circle_segments is not a suitable option. 

Btw for this model 128 segments results in error of assertions.

### Version

0.0.55 - 0.0.57

### What browsers are you seeing the problem on?

Chrome

### Anything else?

[segments.zip](https://github.com/user-attachments/files/16623678/segments.zip)

**Comment by beachtom** [comment]
This has now been fixed
